# Top 10 Comedy picks from IMDb Top 250 (skipping titles already in fm- catalog).
from stories_data import linear_story

ADDED = "2026-06-03T00:00:00Z"

FM_LIFE_IS_BEAUTIFUL = linear_story({
    "id": "fm-life-is-beautiful",
    "title": "A Thousand Points",
    "sourceTitle": "Life Is Beautiful",
    "kind": "movie",
    "synopsis": "A waiter in Arezzo, a librarian he calls Principessa, and a game in a camp that he invents to keep a small boy alive.",
    "releaseYear": 1997, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["war", "father", "italy", "bittersweet"], "rating": 5, "loved": True,
}, [
    ("Brakes on the Hill", "A borrowed car, a salute, a stranger waving a crowd off the road.", "Wave back", "Brave.", "Apologize", "Polite."),
    ("Falling from a Window", "Buongiorno, Principessa, into her arms.", "Ask her name", "Heart.", "Run", "Shy."),
    ("Theater of the Engagement", "She is promised to a fascist clerk in a stiff collar.", "Crash the dinner", "Bold.", "Wait outside", "Honest."),
    ("Pink Horse", "A racehorse painted by night with a slur on its flank.", "Wash it off", "Care.", "Ride it past the dinner", "Wild."),
    ("Books on Shelves", "A library job that lets you smell her hair as you reshelve.", "Linger", "Heart.", "Work fast", "Polite."),
    ("Joshua Born", "A small boy on a kitchen floor with a wooden tank.", "Build a city for him", "Heart.", "Read a paper", "Tired."),
    ("Storefront Painted", "Words on the window of the bookshop you opened.", "Wash them", "Calm.", "Argue", "Pride."),
    ("Train", "A platform, a list, a uniform's calm hand.", "Get on", "Honest.", "Refuse", "Doomed."),
    ("Game", "A thousand points for the first prize, you tell the boy. A real tank.", "Sell it", "Heart.", "Tell him the truth", "Honest."),
    ("German Translation", "A guard speaks rules and you invent them all again for Joshua.", "Translate playfully", "Heart.", "Translate honestly", "Hard."),
    ("Doctor Lessing", "An old riddler from your waiter days, now at the camp in a uniform.", "Ask for help", "Hope.", "Hide", "Wise."),
    ("Soup Line", "A scrap of bread saved in a sleeve for a boy under a bunk.", "Hide it", "Care.", "Eat it", "Hungry."),
    ("Loudspeaker Trick", "A microphone in an office and a message you send across the camp.", "Speak loud", "Heart.", "Stay quiet", "Wise."),
    ("Joshua's Friend", "Another boy, a German child, on the wrong side of a window.", "Encourage friendship", "Heart.", "Discourage it", "Wise."),
    ("Mother's Side", "Dora across the wire and a song carried on a record over a courtyard.", "Play their song", "Heart.", "Hide", "Cautious."),
    ("Bath Sign", "A door marked DOCCIA and a line of small hands.", "Hide Joshua", "Brave.", "Walk in", "Honest."),
    ("Liberation Rumor", "Trucks pulling away in the night and a sound like a country leaving.", "Move now", "Brave.", "Wait", "Cautious."),
    ("Lockup Box", "A cabinet of supplies and a place for Joshua to wait while the camp dies.", "Hide him", "Heart.", "Take him", "Reckless."),
    ("Search for Dora", "A women's barracks and a coat too small.", "Search", "Loyal.", "Run", "Smart."),
    ("Past a Sentry", "Boots on cobbles and a goose-step you turn into a clown's step for the boy in the box.", "Wink at him", "Heart.", "Look straight ahead", "Brave."),
    ("Tank in the Yard", "Dawn, dust, an American crewman with a friendly hand offered down.", "Climb up", "Heart.", "Look for mother first", "Loyal."),
], [
    ("end_won", "A Thousand Points", "Joshua wins his prize, a real tank, an American boy lifting him up. Dora finds him in a market three days later and they go home."),
    ("end_quiet", "Buongiorno, Principessa", "A waiter, a bookseller, a father turning a hard year into a game his son will tell his own children about, hand on a kitchen table."),
    ("end_paint", "Pink Horse, Again", "Joshua paints the pink horse the same color his father did, and rides it through Arezzo at a parade, and people cry without knowing why."),
])

FM_MODERN_TIMES = linear_story({
    "id": "fm-modern-times",
    "title": "Gears",
    "sourceTitle": "Modern Times",
    "kind": "movie",
    "synopsis": "A factory, a paddy wagon, a department store, and a tramp who keeps walking up the road toward the next horizon.",
    "releaseYear": 1936, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["silent", "chaplin", "depression", "tramp"], "rating": 5, "loved": True,
}, [
    ("Lunchtime Test", "A feeding machine your boss bought from a salesman.", "Volunteer", "Reckless.", "Hide", "Smart."),
    ("Conveyor Belt", "Bolts and spinners and a foreman's whistle.", "Keep up", "Brave.", "Slow down", "Honest."),
    ("Gears", "Your body sucked into a wheel like a small leaf.", "Wave on the way", "Calm.", "Scream", "Honest."),
    ("Hospital", "A doctor with a tongue depressor and a long lecture.", "Smile and leave", "Cunning.", "Argue", "Reckless."),
    ("Flag", "A truck loses a red flag and a parade forms behind you.", "Wave it gently", "Honest.", "Drop it", "Wise."),
    ("Cell", "A bunk, a man, a stash of cocaine in a salt shaker.", "Salt your soup", "Reckless.", "Refuse", "Smart."),
    ("Pardon", "The warden offers a recommendation letter to the outside.", "Take it", "Brave.", "Stay in the cell", "Honest."),
    ("Gamin", "A bare-footed girl with a stolen banana and a flashing grin.", "Help her", "Heart.", "Walk on", "Cold."),
    ("Pawnbroker", "Mother's watch on the counter, a few coins back.", "Pawn it", "Practical.", "Refuse", "Honest."),
    ("Shipyard", "A wedge pulled, a hull launched a year early into the harbor.", "Apologize", "Polite.", "Run", "Smart."),
    ("Department Store", "A night watchman job and a roller-skating rink for two.", "Skate blindfolded", "Brave.", "Skate carefully", "Smart."),
    ("Thieves", "Old factory mates turned hungry burglars.", "Share the food", "Honest.", "Call the police", "Cold."),
    ("Shack on the Lake", "A door that falls off in your hand. A roof made of pluck.", "Move in", "Hope.", "Find better", "Wise."),
    ("Newspaper Help-Wanted", "A factory reopens for a single day.", "Apply", "Brave.", "Sleep in", "Tired."),
    ("Strike", "A brick on the cobbles, your shoe on the brick, a passing parade.", "Wave again", "Honest.", "Run", "Smart."),
    ("Cafe Job", "A waiter on roller skates with a tray.", "Take the floor", "Brave.", "Quit", "Smart."),
    ("Performer", "A singing waiter has lost his cuffs with his lyrics on them.", "Mime the song", "Brilliant.", "Sing nonsense", "Wild."),
    ("Authorities at the Door", "Social services for Gamin, paperwork in hand.", "Run with her", "Heart.", "Submit", "Honest."),
    ("Truck on the Highway", "A flatbed, a kindness, two passengers in coats.", "Catch it", "Brave.", "Walk", "Stubborn."),
    ("Open Country", "A road that bends out of frame, sun behind.", "Sing to her", "Heart.", "Just walk", "Honest."),
    ("Smile, She Cries", "A line of dialogue you write on her face with one finger.", "Make her smile", "Heart.", "Hold her hand", "Honest."),
], [
    ("end_road", "Up the Road", "Two figures on a dusty road and a future that has not been built yet. You whistle. She catches up. The two of you take it from there."),
    ("end_cafe", "Waiter on Wheels", "The cafe owner gives you a permanent shift and Gamin a dressing room. The customers wait for the song you have not written yet."),
    ("end_factory", "The Wheel Goes On", "The factory reopens at dawn and you, against your better self, are first in the line. The whistle blows. You smile despite yourself, just barely."),
])

FM_CITY_LIGHTS = linear_story({
    "id": "fm-city-lights",
    "title": "The Flower Girl",
    "sourceTitle": "City Lights",
    "kind": "movie",
    "synopsis": "A tramp, a blind flower girl, a drunken millionaire who only remembers you at night, and a small coin that decides everything.",
    "releaseYear": 1931, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["silent", "chaplin", "love", "kindness"], "rating": 5, "loved": True,
}, [
    ("Statue Unveiled", "A bronze hand on which you have been sleeping.", "Salute", "Polite.", "Climb down", "Smart."),
    ("Flower Stand", "A girl, blind, who mistakes you for a fine gentleman.", "Buy a flower", "Heart.", "Walk past", "Cold."),
    ("Embankment", "A man with a rope and a brick around his neck.", "Stop him", "Brave.", "Hand him a flower", "Polite."),
    ("Mansion", "He insists you stay, drives like a maniac, calls you brother.", "Stay the night", "Brave.", "Slip away", "Wise."),
    ("Morning", "Sober, he does not know you and a butler shows you the door.", "Bow politely", "Polite.", "Argue", "Pride."),
    ("Flower Girl's Window", "Rent overdue, a landlord at the door, soup on the stove.", "Pay it", "Heart.", "Wait", "Honest."),
    ("Boxing Ring", "A fixed match becomes an unfixed match.", "Take the dive", "Practical.", "Fight honestly", "Brave."),
    ("Bell", "Three rounds, knees that won't, a referee in the way.", "Hide behind the ref", "Cunning.", "Throw punches", "Brave."),
    ("Streetcar Home", "Lights and noise and a coin you do not have.", "Walk", "Honest.", "Steal a ride", "Reckless."),
    ("Millionaire Drunk Again", "A car at the curb with a familiar grin and a wad of cash.", "Accept the gift", "Practical.", "Refuse", "Pride."),
    ("Burglary", "Thieves at the mansion and a thousand dollars on the rug.", "Tackle them", "Brave.", "Save the cash for the girl", "Heart."),
    ("Police", "Sirens, a thrown bill, a face at the window.", "Run", "Smart.", "Explain", "Honest."),
    ("Girl's Operation", "A doctor in Vienna who can give her sight.", "Pay him", "Heart.", "Pay the rent first", "Wise."),
    ("Letter Slipped Under", "Love and a note about a long trip.", "Sign it", "Heart.", "Don't", "Cautious."),
    ("Cell", "Months for a theft you did not quite commit.", "Endure", "Brave.", "Snitch", "Cold."),
    ("Release", "A shabby coat, a long shadow, a street that has moved on without you.", "Find her shop", "Heart.", "Walk past", "Honest."),
    ("Flower Shop", "She has a real storefront now and a kind smile for poor strangers.", "Approach", "Brave.", "Watch from the curb", "Shy."),
    ("Quarter", "A small coin she presses into your hand at the door.", "Take it", "Honest.", "Refuse", "Pride."),
    ("Her Fingers", "She touches your hand and a recognition stirs in her face.", "Stay still", "Honest.", "Withdraw", "Frightened."),
    ("Question", "She asks, almost laughing, almost not.", "Nod", "Honest.", "Bow your head", "Shy."),
    ("Smile", "The smallest possible smile, and the last shot of a movie that does not need to say more.", "Smile back", "Heart.", "Look down", "Honest."),
], [
    ("end_yes", "You Can See Now", "She closes her fingers around yours and laughs and laughs, and you both stand in the doorway of a flower shop that smells of gardenia and the future."),
    ("end_walk", "The Long Walk", "You go before she can be ashamed and the bell on her door rings behind you and the street takes you back. The film ends on a frame of empty pavement."),
    ("end_friend", "Friend of the Shop", "You become her quiet best customer, never said for what you are. She finds out, decades later, from a letter in a drawer."),
])

FM_GREAT_DICTATOR = linear_story({
    "id": "fm-great-dictator",
    "title": "The Barber of the Ghetto",
    "sourceTitle": "The Great Dictator",
    "kind": "movie",
    "synopsis": "A Jewish barber, an identical dictator, a balloon globe in an office, and a microphone that changes hands at the worst possible moment.",
    "releaseYear": 1940, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["satire", "chaplin", "war", "speech"], "rating": 5, "loved": True,
}, [
    ("Trench", "A long gun, a comrade, the wrong line of the parapet.", "Aim away", "Mercy.", "Fire", "Soldier."),
    ("Lost in the Fog", "Generations later you wake up in a hospital that no longer exists.", "Walk home", "Stubborn.", "Wait", "Cautious."),
    ("The Shop", "Dust, a sign, a customer with a Hynkel armband at the door.", "Be polite", "Wise.", "Refuse to serve", "Brave."),
    ("Hannah Next Door", "A pan of soup, a courtyard, a hope that survived a war.", "Talk to her", "Heart.", "Hide", "Shy."),
    ("Schultz, Saved", "A pilot you carried out of a burning fuselage in another life.", "Greet him", "Honor.", "Pretend not to know", "Wise."),
    ("Storm Troopers", "Boys in armbands with bricks and brushes.", "Scrub the slur off", "Honest.", "Hide", "Cautious."),
    ("Brush in His Eye", "A confrontation in a stairwell with a pail of paint.", "Apologize", "Wise.", "Swing", "Brave."),
    ("Schultz's Apartment", "Tea, a confession, plans for a long resistance.", "Join him", "Brave.", "Decline", "Honest."),
    ("Hynkel's Office", "Across town, you have inadvertently inspired a coin balanced on a globe.", "Watch the office", "Patient.", "Bide", "Wise."),
    ("Pretzels in the Pudding", "A coin in a dessert at a barber's table determines who assassinates the dictator.", "Take a pudding", "Brave.", "Pass", "Cautious."),
    ("Schultz Arrested", "A black truck at the door and a captain in white gloves.", "Hide him", "Loyal.", "Refuse to help", "Cold."),
    ("Hannah on the Roof", "Laundry lines, a song, a promise to find each other in a free country.", "Promise", "Heart.", "Don't", "Honest."),
    ("Border", "Trucks, papers, a wide gray river to a kinder country.", "Cross", "Brave.", "Stay", "Loyal."),
    ("Pickup", "A military car, a salute mistaking you for the dictator.", "Salute back", "Cunning.", "Refuse", "Honest."),
    ("Tomanian Forces Massed", "A parade you have been driven into the center of.", "Wave", "Cunning.", "Bolt", "Reckless."),
    ("Stadium Tunnel", "Drums, music, a long ramp toward a microphone.", "Walk forward", "Brave.", "Refuse the stage", "Honest."),
    ("Garbitsch's Introduction", "He praises Hynkel; the world goes quiet to hear him.", "Wait", "Patient.", "Cut him off", "Bold."),
    ("Microphone", "A small black bulb, an open sky, a continent waiting for a voice.", "Speak gently", "Brave.", "Speak with rage", "Honest."),
    ("Hannah on the Radio", "Far away she is on her knees in a field hearing your voice for the first time in months.", "Speak to her", "Heart.", "Speak to all of them", "Honest."),
    ("Words", "A speech about kindness in a uniform that does not deserve it.", "Soldiers, do not despair", "Brave.", "Be brief", "Wise."),
    ("Last Line", "Look up, Hannah. The clouds are lifting.", "Say it", "Heart.", "Stop", "Honest."),
], [
    ("end_speech", "Look Up, Hannah", "The crowd is quiet for once, and somewhere a woman on a hillside stands up. The film cuts to her face, and the future is, for one second, possible."),
    ("end_barber", "Back to the Shop", "You return to the chair and the strop, and a man in an armband comes in to threaten you and finds Schultz waiting for him, smiling."),
    ("end_quiet", "Hannah at the Door", "She knocks at your shop a year after the war and you do not recognize her at first, both of you laughing at how thin you became."),
])

FM_SOME_LIKE_IT_HOT = linear_story({
    "id": "fm-some-like-it-hot",
    "title": "Nobody's Perfect",
    "sourceTitle": "Some Like It Hot",
    "kind": "movie",
    "synopsis": "Two musicians, a massacre witnessed, a girl's band on a train, and a millionaire on a yacht who is not easy to discourage.",
    "releaseYear": 1959, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["screwball", "disguise", "gangsters", "wilder"], "rating": 5, "loved": True,
}, [
    ("Garage", "Chicago, 1929, machine guns and a snow boot stuck on a wet floor.", "Run", "Smart.", "Hide", "Brave."),
    ("Booking Agent", "Sweet Sue's Society Syncopators, Florida, three weeks of bus rides.", "Take the gig", "Reckless.", "Refuse", "Honest."),
    ("Heels", "Borrowed dresses, borrowed wigs, names like Josephine and Daphne.", "Walk small", "Cunning.", "Strut", "Bold."),
    ("Train Berth", "Sugar Kane, a flask, a ukulele.", "Help her hide it", "Friend.", "Stay still", "Smart."),
    ("Late Night", "A whole band in your berth with a hot water bottle and a salami.", "Host them", "Heart.", "Throw them out", "Wise."),
    ("Hotel Lobby", "A retiree named Osgood who likes your ankles.", "Refuse politely", "Polite.", "Encourage him", "Mischievous."),
    ("Beach", "Shell collectors and a borrowed Cary Grant accent.", "Pretend to be him", "Cunning.", "Stay safe", "Wise."),
    ("Yacht", "Osgood's tender pulls up and Daphne is invited to dance the night away.", "Send her", "Cunning.", "Cancel", "Wise."),
    ("Tango", "A rose, a tilt, twelve hours that pass like four.", "Lead", "Bold.", "Follow", "Wise."),
    ("Sugar in Tears", "Engagement to a fictional Shell Oil heir falling apart on a yacht.", "Comfort her", "Heart.", "Confess", "Honest."),
    ("Hotel Bath", "A scene of female solidarity that requires you to keep a beard pressed against your sternum.", "Stay still", "Smart.", "Bolt", "Honest."),
    ("Convention", "Friends of Italian Opera with familiar faces and bulgy coats in the lobby.", "Disguise harder", "Cunning.", "Run", "Smart."),
    ("Press Conference for Spats", "A coffin and a cake and a hidden cake-jumping gunman.", "Hide", "Smart.", "Watch", "Reckless."),
    ("Banquet", "A cake bursting open with a Tommy gun and Spats Columbo's last objection.", "Crawl out", "Smart.", "Stay frozen", "Honest."),
    ("Stairs", "A bellboy with a knowing look and the wrong color of wig.", "Tip him", "Practical.", "Push past", "Wild."),
    ("Boat", "Osgood at the wheel, a Sugar at the dock, a small bag of clothes.", "Tell Sugar everything", "Honest.", "Sneak aboard", "Cowardly."),
    ("Pier", "Sugar running, the bass case bouncing, the music starting up again.", "Wait for her", "Heart.", "Cast off", "Cold."),
    ("Engine", "Osgood at the throttle, the harbor opening.", "Confess at last", "Honest.", "Stay in character", "Cunning."),
    ("Wig Off", "A breeze, a real face, a calm look at the engineer.", "Tell him the truth", "Brave.", "Hold the wig down", "Cowardly."),
    ("Reasons", "Smoker, never could have children, an entire list.", "Try harder", "Honest.", "Surrender", "Wise."),
    ("Nobody's Perfect", "He shrugs at the wheel and the boat goes on toward open water.", "Laugh", "Heart.", "Cry", "Honest."),
], [
    ("end_three", "Florida by Boat", "Sugar at the bow, Daphne at the stern, Osgood at the helm. None of you knows what the next harbor looks like, and all of you agree to look together."),
    ("end_sugar", "Sugar and the Bass", "You and Sugar slip off at the next pier into a small life with a small band and a small apartment and a very large amount of love."),
    ("end_solo", "Joe Alone", "You go ashore at a strange town with no act and no friends and you start an honest life that nobody, including you, expected."),
])

FM_SINGIN_IN_RAIN = linear_story({
    "id": "fm-singin-in-rain",
    "title": "A Glorious Feeling",
    "sourceTitle": "Singin' in the Rain",
    "kind": "movie",
    "synopsis": "A silent star, a starlet with a terrible voice, a chorus girl with talent, and the day the talkies arrived in Hollywood.",
    "releaseYear": 1952, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["musical", "hollywood", "rain", "talkies"], "rating": 5, "loved": True,
}, [
    ("Hollywood Premiere", "Klieg lights, a sentence read off a card.", "Lie gracefully", "Cunning.", "Be honest", "Awkward."),
    ("Lina at the Mic", "A voice that could clear a room.", "Charm her", "Polite.", "Avoid her", "Cold."),
    ("Cosmo at the Piano", "A friend with a quip ready for any disaster.", "Listen", "Heart.", "Brush him off", "Cold."),
    ("Streetcar", "A girl with a chip on her shoulder named Kathy.", "Apologize", "Honest.", "Pursue her", "Bold."),
    ("Soundstage Sneeze", "A microphone in a bouquet picks up a sneeze in the back row.", "Mark the spot", "Wise.", "Yell at the boom op", "Hot."),
    ("Talking Picture", "The studio panics; the next one must talk.", "Embrace it", "Brave.", "Resist it", "Cautious."),
    ("Diction Lessons", "Round vowels, sharp consonants, an instructor with a tape ruler.", "Sing the lesson", "Joyful.", "Recite", "Honest."),
    ("Lina's Lockup", "Producers want to keep her voice a secret.", "Help them", "Loyal.", "Confide in Kathy", "Honest."),
    ("Dub Plan", "Kathy at a microphone behind the curtain.", "Persuade her", "Smart.", "Drop the plan", "Honest."),
    ("Sneak Preview", "A theater of jeers because the sound is six frames off.", "Take notes", "Cool.", "Walk out", "Pride."),
    ("Editing Bay", "A loop, a cue, a chance to rebuild the picture as a musical.", "Try it", "Brave.", "Cut your losses", "Cautious."),
    ("Wardrobe", "Tap shoes, a sequined coat, an idea about a Broadway montage.", "Lead the number", "Joyful.", "Stay backstage", "Shy."),
    ("Lina's Tantrum", "A contract clause, a lawyer, a finger on your script.", "Stand firm", "Brave.", "Concede", "Wise."),
    ("Rain on the Street", "A streetlamp, an umbrella, a chorus you can almost hear.", "Sing it", "Joyful.", "Walk", "Tired."),
    ("Kathy at the Door", "She slips out without saying goodbye.", "Chase her", "Heart.", "Let her go", "Wise."),
    ("Yes Yes", "Cosmo at the piano in a half-empty studio with a song about agreement.", "Sing along", "Joyful.", "Sit down", "Tired."),
    ("Premiere Two", "A whole second crowd in dresses and tuxes for the talkie premiere.", "Stay calm", "Wise.", "Sweat", "Honest."),
    ("Lina on the Mic", "Reporters insist she sing live.", "Pull the curtain", "Cunning.", "Save her", "Mercy."),
    ("Curtain Up", "Kathy at the second mic behind the screen, oblivious to the trick about to be played.", "Tell her", "Honest.", "Don't", "Cowardly."),
    ("Reveal", "The curtain rises and a thousand faces realize who is actually singing.", "Walk on stage", "Brave.", "Hide", "Cowardly."),
    ("Billboard", "Don and Kathy on a giant poster downtown, an umbrella between them.", "Kiss her there", "Joyful.", "Smile", "Wise."),
], [
    ("end_rain", "Singin' in the Rain", "You spin the umbrella at the curb and a cop watches you, baffled, and the camera pulls back and the city goes on at half speed for one impossible chorus."),
    ("end_credit", "Kathy on the Card", "Her name above the title, a vocal coach for Lina across town, and a contract with two clauses about respect and one about lunch."),
    ("end_cosmo", "Make 'Em Laugh", "Cosmo gets his own picture and a sandwich named for him at the studio commissary, and you eat one every Friday for the rest of your career."),
])

FM_TOY_STORY = linear_story({
    "id": "fm-toy-story",
    "title": "To Infinity",
    "sourceTitle": "Toy Story",
    "kind": "movie",
    "synopsis": "A cowboy doll, a new space ranger, a kid named Andy, and a road trip across a backyard fence that ends at a pizza place.",
    "releaseYear": 1995, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["pixar", "toys", "friendship", "kids"], "rating": 5, "loved": True,
}, [
    ("Birthday Plans", "Andy's mother carries cake into a living room while you organize a recon.", "Send the soldiers", "Smart.", "Hide", "Cautious."),
    ("Box Sees Wings", "A space ranger with retracting plastic wings is the surprise gift.", "Welcome him", "Polite.", "Resent him", "Honest."),
    ("Andy's Bed", "He pins a new poster on the ceiling above where you used to sleep.", "Stay friendly", "Honest.", "Be petty", "Pride."),
    ("Window Push", "An accidental shove that becomes a real fall.", "Confess", "Honest.", "Hide the deed", "Cowardly."),
    ("Lost in the Yard", "A space ranger thinks the gas pump is a planet.", "Play along", "Mercy.", "Correct him", "Hard."),
    ("Pizza Planet", "A rocket-shaped truck, a chance to get back into the house.", "Hide in the back", "Smart.", "Wait at the curb", "Cautious."),
    ("Claw Machine", "Squeaky aliens worship a mechanical claw.", "Climb in", "Brave.", "Wait outside", "Cautious."),
    ("Sid's Bedroom", "A boy with a magnifying glass and a love of explosives.", "Be still", "Smart.", "Make a plan", "Brave."),
    ("Mutant Toys", "A spider with a doll head and a fishing pole with a baby leg.", "Don't be afraid", "Brave.", "Run", "Cowardly."),
    ("Backpack", "Sid plans to strap a rocket to a new space ranger.", "Tell Buzz", "Honest.", "Hide", "Cowardly."),
    ("Toy Roar", "An organized swarm in the yard tells a small boy a hard lesson.", "Lead them", "Brave.", "Hold back", "Cautious."),
    ("Moving Truck", "Andy's family rolls out and the rest of the toys are already aboard.", "Run for it", "Brave.", "Give up", "Tired."),
    ("RC Car", "A remote control speedster, a chase down a suburban street.", "Cheer Buzz on", "Friend.", "Sabotage him", "Cold."),
    ("Out of Batteries", "RC's lights dim halfway up the block.", "Stop", "Honest.", "Push harder", "Stubborn."),
    ("Match Strike", "A toy soldier's helmet, a rocket fuse, an idea about altitude.", "Light it", "Brave.", "Save the match", "Wise."),
    ("Up", "Wings open. A whoosh. A backyard receding.", "Glide", "Brave.", "Falter", "Frightened."),
    ("Into the Box", "Bo Peep and the slinky dog cheering through cardboard.", "Land", "Heart.", "Hover", "Pride."),
    ("Christmas Morning", "A new round of presents, a hush of anticipation.", "Stand together", "Friend.", "Brace alone", "Cold."),
    ("Andy's Bedroom Again", "A puppy named Buster downstairs.", "Welcome him", "Heart.", "Hide", "Cautious."),
    ("First Wave", "A toy you don't recognize on the floor.", "Introduce yourself", "Polite.", "Stay back", "Wise."),
    ("Old Friends", "Buzz at your shoulder. The new toys at your other. A whole bedroom of allies.", "Smile", "Heart.", "Stay quiet", "Honest."),
], [
    ("end_friend", "Friend in Me", "You and Buzz watch a new toy meet Andy and you remember what it felt like, and you decide to be the welcoming committee from now on, forever."),
    ("end_yard", "The Yard Adventure", "You and Buzz become the team that handles backyard rescues, and the toys talk about you both like a small fire department."),
    ("end_quiet", "Andy Asleep", "The kid is dreaming. Buzz hums the theme from the commercial. You sit on the edge of the bed and you do not, for once, plan anything."),
])

FM_APARTMENT = linear_story({
    "id": "fm-apartment",
    "title": "Shut Up and Deal",
    "sourceTitle": "The Apartment",
    "kind": "movie",
    "synopsis": "An office worker, a key lent to bosses, a sad elevator girl, and a New Year's Eve that finally chooses a person.",
    "releaseYear": 1960, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["wilder", "office", "lonely", "newyear"], "rating": 5, "loved": True,
}, [
    ("Cold Hallway", "Locked out of your own apartment by Mr. Kirkeby and a date.", "Wait under the awning", "Polite.", "Knock", "Bold."),
    ("Promotion Memo", "Four executives have put in a word with Mr. Sheldrake.", "Smile and accept", "Strategic.", "Hesitate", "Honest."),
    ("Elevator", "Fran Kubelik says hello in a voice that takes a small piece of your day with it.", "Speak", "Heart.", "Stay polite", "Shy."),
    ("Compact Mirror", "A small crack in the lid that you have seen before in a key drawer.", "Recognize it", "Honest.", "Pretend not to", "Wise."),
    ("Sheldrake's Office", "A glass-walled office and a sentence about your key.", "Negotiate", "Practical.", "Refuse", "Honest."),
    ("Chinese Restaurant", "Fran in a borrowed coat over a hat with a feather.", "Be patient", "Wise.", "Be witty", "Light."),
    ("Christmas Eve", "Office party, paper cups, a quiet cubicle with a tear in it.", "Sit with her", "Heart.", "Make a joke", "Light."),
    ("Apartment, Night", "Sleeping pills, an unfinished glass, a body that is breathing too slow.", "Call a doctor", "Brave.", "Wait", "Cowardly."),
    ("Dr. Dreyfuss", "A neighbor who has seen too many of your parties and one more.", "Apologize", "Honest.", "Stay silent", "Cold."),
    ("Spaghetti Strainer", "A makeshift colander, a long night of soup and small talk.", "Tell jokes", "Heart.", "Be quiet", "Honest."),
    ("Sheldrake's Promise", "He will leave his wife by spring, he says, with a hand on his tie.", "Believe him", "Hopeful.", "Doubt", "Wise."),
    ("Cards", "Gin rummy on the coffee table with a girl in your bathrobe.", "Let her win", "Heart.", "Play to win", "Honest."),
    ("Doctor's Note", "Stomach pumped on a Christmas Eve. The neighbors are watching.", "Take a stand", "Brave.", "Stay quiet", "Cowardly."),
    ("New Promotion", "A key to the executive washroom and a corner desk.", "Accept", "Strategic.", "Decline", "Honest."),
    ("Sheldrake's Date", "He brings Miss Olsen, his secretary, to the office party.", "Watch", "Patient.", "Confront", "Brave."),
    ("Olsen on the Phone", "Years of his promises, in a sentence she shares with Mrs. Sheldrake.", "Sympathize", "Honest.", "Stay out", "Cold."),
    ("Hat in Hand", "Sheldrake at your office door asking for the key one more night.", "Refuse", "Brave.", "Give it up", "Cowardly."),
    ("Key on the Desk", "A small object that you slide back across his blotter.", "Walk out", "Honest.", "Pause", "Tired."),
    ("Apartment, Packing", "Suitcase open, lamp still on, a knock on the door.", "Open it", "Brave.", "Pretend not to be in", "Cowardly."),
    ("Fran on the Stairs", "A coat, a hat, a small smile at the bottom of a step.", "Step aside", "Polite.", "Hold the door", "Heart."),
    ("Shut Up and Deal", "Cards on the rug, a glass on the table, a wordless promise.", "Deal", "Heart.", "Speak", "Honest."),
], [
    ("end_deal", "Shut Up and Deal", "Cards keep falling. Neither of you says it for a year. By then you don't need to. The neighbors approve. The neighbors had a betting pool."),
    ("end_quit", "New Year, New Job", "You walk into an office across town with a small reference letter and a lighter shoulder, and you build a life that doesn't require a key to anyone else's place."),
    ("end_fran", "Fran's Bakery", "She opens a small place on a side street. You bus the tables on weekends. The strainer hangs above the counter like a chandelier."),
])

FM_AMELIE = linear_story({
    "id": "fm-amelie",
    "title": "The Glass Man's List",
    "sourceTitle": "Amélie",
    "kind": "movie",
    "synopsis": "A shy waitress at the Two Windmills, a tin box of childhood treasures, and a man in a glass house who has been waiting for someone to listen.",
    "releaseYear": 2001, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["french", "whimsy", "kindness", "love"], "rating": 5, "loved": True,
}, [
    ("Tin Box", "A bathroom tile shifts and a small treasure of a stranger's childhood falls into your hand.", "Return it", "Heart.", "Keep it", "Curious."),
    ("Telephone Booth", "A phone rings and a stranger answers a question he has been carrying for forty years.", "Watch", "Honest.", "Walk on", "Shy."),
    ("Father's Garden Gnome", "A glance at a stuck life and a passport in your hand.", "Send the gnome traveling", "Mischievous.", "Leave it", "Wise."),
    ("Glass Man", "An older neighbor whose bones break too easily, painting the same Renoir.", "Visit him", "Friend.", "Pass", "Shy."),
    ("Bal du Moulin de la Galette", "A figure in a painting he can never quite place.", "Bring him a tape", "Heart.", "Bring a book", "Practical."),
    ("Gina at the Cafe", "Sad, witty, on the lookout for a kinder regular.", "Match-make", "Cunning.", "Stay out of it", "Wise."),
    ("The Hypochondriac", "A regular with a list of imaginary symptoms.", "Tease him", "Light.", "Sympathize", "Honest."),
    ("Joseph", "An ex of Gina's who keeps a notebook of her laughter.", "Distract him", "Cunning.", "Confront him", "Brave."),
    ("Photobooth Album", "Pages of discarded passport photos, no two from the same face.", "Investigate", "Curious.", "Borrow it", "Bold."),
    ("Nino", "A man at the metro pasting torn pieces back together.", "Approach", "Bold.", "Watch", "Shy."),
    ("Lost Album Returned", "A blue arrow on a fence, a chase on a moped, a clue in a small voice.", "Hide", "Mischievous.", "Speak", "Honest."),
    ("Tin Box Reunion", "Bretodeau in a phone booth weeping into his own childhood.", "Stay nearby", "Heart.", "Walk away", "Wise."),
    ("Grocer's Bullying", "Collignon humiliates his apprentice Lucien at the produce stand.", "Switch his alarm clock", "Mischievous.", "Stay out of it", "Wise."),
    ("Toothpaste Trick", "Slippers, doorknob, light bulb, all subtly altered.", "Do it gleefully", "Mischievous.", "Stop", "Honest."),
    ("Glass Man's Letter", "A monologue about the man across the courtyard who needs to stop watching.", "Read it aloud to Nino", "Heart.", "Mail it", "Mercy."),
    ("Father's Postcard", "A gnome at the Eiffel Tower, the Pyramids, Moscow.", "Frame it", "Heart.", "Hide it", "Shy."),
    ("Cafe Date", "Nino at a table inside the Two Windmills, eyes on the door.", "Watch from the back", "Shy.", "Sit down", "Brave."),
    ("Cigarette Vendor", "Georgette tries to wave him over while you panic.", "Send him a clue", "Cunning.", "Stop the game", "Honest."),
    ("Moped to the Door", "A doorbell and a chance to finally not run.", "Open it", "Brave.", "Hide in the kitchen", "Shy."),
    ("Three Kisses", "A small ritual learned over a tape with a Renoir.", "Lean in", "Heart.", "Wait", "Shy."),
    ("Rooftops at Dawn", "A camera moves across Paris, smiling at things small enough to matter.", "Smile back", "Heart.", "Look down", "Honest."),
], [
    ("end_kiss", "Three Times", "Two cheeks and a forehead, and a moped pulling away from the curb, and a courtyard that has, finally, a sound of laughter in it."),
    ("end_tin", "Tin Box on a Shelf", "You start a small museum of returned objects above your bed. People come to see it from across the arrondissement. You blush every time."),
    ("end_paint", "The Renoir Solved", "The Glass Man finishes the painting at last. He looks at it and laughs and cries and offers you a glass of milk. You take it."),
])

FM_GRAND_BUDAPEST = linear_story({
    "id": "fm-grand-budapest",
    "title": "The Hotel and the Painting",
    "sourceTitle": "The Grand Budapest Hotel",
    "kind": "movie",
    "synopsis": "A concierge, a lobby boy, an inheritance scandal, a painting of a boy with an apple, and a long sled ride down an alpine slope.",
    "releaseYear": 2014, "addedAt": ADDED, "genre": "Comedy",
    "tags": ["wes-anderson", "hotel", "caper", "europe"], "rating": 5, "loved": True,
}, [
    ("Reception", "A small lobby boy named Zero asks for a job from a desk.", "Hire him", "Cunning.", "Defer", "Cautious."),
    ("Madame D.", "A dowager with a long fur, a tearful goodbye, a key to a safe.", "Reassure her", "Heart.", "Be cold", "Polite."),
    ("Will Reading", "A family of vultures and a clause that names you.", "Accept it", "Brave.", "Refuse", "Wise."),
    ("Boy With Apple", "A small panel painting that everyone wants to keep nailed to the wall.", "Steal it", "Cunning.", "Wait", "Honest."),
    ("Dmitri", "A son with a leather coat and a man named Jopling who carries a knife.", "Antagonize him", "Brave.", "Placate him", "Wise."),
    ("Train", "A papers check and a uniform with a scar from the Old War.", "Speak up for Zero", "Loyal.", "Stay still", "Cowardly."),
    ("Police Order", "A telegram arrests you for the murder of Madame D.", "Surrender quietly", "Wise.", "Bolt", "Reckless."),
    ("Prison Cell", "A roommate named Ludwig with a tattoo of a map of the world.", "Trade pastries for tools", "Cunning.", "Wait", "Patient."),
    ("Mendl's Box", "Agatha bakes you out a hammer in a tarte aux mille feuilles.", "Use it", "Brave.", "Save it", "Cautious."),
    ("Sewer Run", "A long stinking pipe under a cobbled square.", "Run", "Brave.", "Crawl", "Smart."),
    ("Society of the Crossed Keys", "A network of concierges with a passcode and an emergency line.", "Call them", "Wise.", "Wait", "Patient."),
    ("Monastery", "A chamber with monks and a man named Serge holding a confession in his hand.", "Reassure him", "Heart.", "Threaten him", "Cold."),
    ("Sled Chase", "Wood runners, a downhill, a man with a knife on the next track.", "Cut a corner", "Brave.", "Hold the line", "Smart."),
    ("Boy With Apple, Again", "Hidden behind a much worse painting in your suite.", "Reveal it", "Bold.", "Sell it", "Practical."),
    ("Lobby Coup", "Soldiers in the lobby, a checkpoint at the desk.", "Bluff", "Cunning.", "Hide", "Cautious."),
    ("Train, Again", "Papers, lobby boy, a familiar scar in a higher rank.", "Speak the password", "Honor.", "Stay quiet", "Cowardly."),
    ("Will Hidden", "A second testament in the back of the painting.", "Read it aloud", "Brave.", "Burn it", "Cold."),
    ("Pastry Shop", "Agatha at the counter, flour on her brow, a small kiss on the back of your wrist.", "Hold the moment", "Heart.", "Run", "Smart."),
    ("Roof", "Jopling at the parapet, a bell tower, a tilt forward.", "Push", "Final.", "Hold him", "Honest."),
    ("Council Room", "The will read, the painting returned, the hotel inherited, Dmitri sputtering.", "Toast", "Joyful.", "Stay solemn", "Polite."),
    ("Last Train", "A border, a uniform, a smaller scar.", "Stand", "Honor.", "Sit down", "Wise."),
], [
    ("end_pink", "Pink Hotel, Glorious Dawn", "You manage the Grand Budapest into a small renaissance and Zero takes over after you, and Agatha bakes things that make people cry on the lobby steps."),
    ("end_zero", "Zero Tells the Story", "Decades later a lobby boy who once was small tells a young writer about a concierge with cologne and a pencil mustache, and a country he no longer recognizes."),
    ("end_paint", "Boy With Apple on the Wall", "The painting hangs in your suite forever and Dmitri spends his last years in a small angry apartment with a postcard of it on the mantel."),
])

COMEDY_SPECS = [FM_LIFE_IS_BEAUTIFUL, FM_MODERN_TIMES, FM_CITY_LIGHTS, FM_GREAT_DICTATOR, FM_SOME_LIKE_IT_HOT,
                FM_SINGIN_IN_RAIN, FM_TOY_STORY, FM_APARTMENT, FM_AMELIE, FM_GRAND_BUDAPEST]
