# Top 10 Horror picks from IMDb Top 250 (skipping titles already in fm- catalog).
from stories_data import linear_story

ADDED = "2026-06-03T00:00:00Z"

FM_SHINING = linear_story({
    "id": "fm-shining",
    "title": "All Work and No Play",
    "sourceTitle": "The Shining",
    "kind": "movie",
    "synopsis": "A winter caretaker, an empty hotel, a boy on a tricycle, and a corridor that has been waiting for the right family.",
    "releaseYear": 1980, "addedAt": ADDED, "genre": "Horror",
    "tags": ["kubrick", "haunting", "snow", "family"], "rating": 5, "loved": True,
}, [
    ("The Interview", "Mr. Ullman across a desk and a story about a previous caretaker.", "Accept", "Brave.", "Refuse", "Wise."),
    ("Tour", "Long carpets, a maze made of hedges, twin girls watching from a hallway.", "Smile politely", "Polite.", "Stare back", "Honest."),
    ("Hallorann", "A cook with a kind grin and a word for a boy who shines.", "Listen", "Honest.", "Brush past", "Polite."),
    ("Tricycle", "Danny on plastic wheels over carpet and linoleum.", "Let him ride", "Mercy.", "Send him to bed", "Cautious."),
    ("Bathroom Mirror", "Danny's lips form the word that lives in mirrors.", "Hold him", "Heart.", "Look away", "Cowardly."),
    ("Wendy in the Kitchen", "Soup, a quiet smile, a husband upstairs typing nothing for hours.", "Talk to her", "Honest.", "Stay quiet", "Cold."),
    ("Lounge Bar", "A bartender named Lloyd at an empty bar.", "Order", "Tempted.", "Walk out", "Wise."),
    ("Room 237", "A door at the end of a hall and a hand on the knob.", "Open it", "Reckless.", "Walk away", "Wise."),
    ("Twin Girls", "End of a corridor, hand in hand, a quiet invitation.", "Run", "Smart.", "Approach", "Reckless."),
    ("Typewriter Page", "A novel of one sentence repeated to the bottom of every page.", "Hide the manuscript", "Brave.", "Read it aloud", "Honest."),
    ("Wendy's Bat", "A wife on a staircase with a Louisville and a tear.", "Step back", "Wise.", "Step forward", "Hard."),
    ("Storage Room", "A latch, a dark room, the smell of canned peaches.", "Plead through the door", "Honest.", "Curse her", "Cold."),
    ("Hallorann Drives", "A snowcat from Florida headed for trouble.", "Wait for him", "Hope.", "Pre-empt", "Hard."),
    ("Danny's REDRUM", "A word on a door in lipstick.", "Read it in the mirror", "Honest.", "Wipe it off", "Cowardly."),
    ("Hallorann at the Lobby", "He calls Danny's name and a fire axe answers.", "Help him", "Brave.", "Hide", "Cowardly."),
    ("Hedge Maze", "Snow up to your knees, prints in front of you that are your own.", "Backtrack", "Smart.", "Press on", "Stubborn."),
    ("Wendy on the Snowcat", "A keyhole, a stalling engine, a son in her arms.", "Help her start it", "Mercy.", "Smash a window", "Hard."),
    ("Ghost Ball", "A grand staircase, music, a waiter who has been here longer than the carpet.", "Dance", "Tempted.", "Decline", "Honest."),
    ("Photograph in the Lobby", "1921, a man at the front of a New Year's crowd, your own face.", "Walk past", "Wise.", "Stand and stare", "Honest."),
    ("Lock-In", "A snow-shut window, a wife banging at a door, a small voice calling Daddy.", "Open the door", "Mercy.", "Wait", "Honest."),
    ("Maze, Center", "Two sets of footprints in, one set out, a heartbeat slowing in the dark.", "Sit down", "Tired.", "Get up", "Brave."),
], [
    ("end_thaw", "Spring at the Overlook", "Tradesmen find an axe by the boiler and a manuscript in a typewriter and a photograph in the lobby that nobody can quite explain."),
    ("end_drive", "Snowcat South", "Wendy at the wheel and Danny in the passenger seat. They roll out of the gates and never come back, not even for the manuscript."),
    ("end_quiet", "Hallorann Hires a Cook", "He drives away from the Overlook with a small boy and a half-broken wife and he teaches the boy to read recipes, and the shine, slowly, becomes a small private gift."),
])

FM_ALIEN = linear_story({
    "id": "fm-alien",
    "title": "In Space No One",
    "sourceTitle": "Alien",
    "kind": "movie",
    "synopsis": "A space tug, a distress beacon, an egg, and a chest cavity that does not appreciate visitors.",
    "releaseYear": 1979, "addedAt": ADDED, "genre": "Horror",
    "tags": ["space", "creature", "ripley", "claustrophobic"], "rating": 5, "loved": True,
}, [
    ("Mother", "A signal at the edge of charted space.", "Wake the crew", "Discipline.", "Sleep through", "Lazy."),
    ("LV-426", "A rocky moon under a yellow sky and a horseshoe ship in the dust.", "Land", "Brave.", "Wait in orbit", "Cautious."),
    ("Field of Eggs", "Leathery shapes in fog with a thing twitching beneath each lid.", "Step back", "Wise.", "Lean in", "Reckless."),
    ("Facehugger", "A spider with a tail wraps a man's helmet.", "Stay outside", "Brave.", "Open the door", "Mercy."),
    ("Quarantine", "Ripley at the door. Ash at the latch.", "Side with Ripley", "Discipline.", "Override the lock", "Mercy."),
    ("Medbay", "A facehugger drops off and walks itself into a corner.", "Burn it", "Hard.", "Cage it", "Wise."),
    ("Dinner", "Kane laughs at the table about a long sleep ahead.", "Sit close", "Friend.", "Stay back", "Wary."),
    ("Chestburst", "A small wet thing on the table running for a vent.", "Pursue", "Brave.", "Brace", "Smart."),
    ("Vent Map", "Air ducts and a tracker that pings irregularly.", "Use the tracker", "Smart.", "Hunt by ear", "Reckless."),
    ("Brett's Cat", "Jonesy hisses at a door that should not be unlocked.", "Follow Jonesy", "Wise.", "Ignore the cat", "Cold."),
    ("Brett Gone", "A wet sound up in the chains.", "Run", "Smart.", "Look up", "Reckless."),
    ("Dallas in the Vents", "Captain in coveralls with a flame thrower.", "Talk to him on comms", "Friend.", "Stay quiet", "Cautious."),
    ("Special Order 937", "Mother's screen reveals the crew is expendable.", "Confront Ash", "Brave.", "Hide your knowledge", "Cunning."),
    ("Ash, Synthetic", "A magazine rolled in his hand, white fluid on his collar.", "Decapitate him", "Brave.", "Talk first", "Wise."),
    ("Reactivate Ash's Head", "He laughs at your odds.", "Listen carefully", "Wise.", "Burn him", "Cold."),
    ("Self-Destruct", "A countdown, a long corridor, a thing in the way.", "Set it", "Final.", "Wait", "Cautious."),
    ("Cat Carrier", "Jonesy under a chair in a service bay.", "Grab him", "Heart.", "Leave him", "Cold."),
    ("Lambert and Parker", "A scream, an impact, a corridor that goes quiet too fast.", "Push past", "Smart.", "Try to help", "Loyal."),
    ("Narcissus Lifeboat", "A small bay, a small ship, an escape that fits two if one is a cat.", "Buckle in", "Smart.", "Wait", "Honest."),
    ("Bridge", "The alien folded into a wall plate behind the seats.", "Vent the cabin", "Brave.", "Wait", "Honest."),
    ("Final Report", "A log entry to a Company recorder no one will check for fifty-seven years.", "Tell the truth", "Honest.", "Lie a little", "Wise."),
], [
    ("end_log", "Final Log", "Ripley, Nostromo, signing off. The cat curls against your boot and the cryo bay hums and you sleep without dreams for the first time in months."),
    ("end_hold", "Hyper Sleep", "You and Jonesy drift through space toward a frontier station, half a century out, a small lifeboat and a clean ledger of survival."),
    ("end_quiet", "Cat in the Tube", "You wake up to find Jonesy purring against the glass of his cryo tube and you both look at each other for a long calm second before you go back under."),
])

FM_THING = linear_story({
    "id": "fm-thing",
    "title": "Who Goes There",
    "sourceTitle": "The Thing",
    "kind": "movie",
    "synopsis": "An Antarctic research station, a Norwegian helicopter, and a thing that imitates anything it touches.",
    "releaseYear": 1982, "addedAt": ADDED, "genre": "Horror",
    "tags": ["carpenter", "ice", "paranoia", "shapeshift"], "rating": 5, "loved": True,
}, [
    ("Norwegian Pursuit", "A helicopter hunts a dog across white tundra with a rifle.", "Take cover", "Smart.", "Shoot back", "Brave."),
    ("Camp Dog", "The husky comes in calm, eyes too bright.", "Cage it", "Wise.", "Pet it", "Reckless."),
    ("Norwegian Camp", "A burned man in a chair, a wall of melted instruments.", "Photograph", "Wise.", "Search the labs", "Brave."),
    ("Block of Ice", "A negative of a body cut from the floor.", "Bring it back", "Curious.", "Leave it", "Wise."),
    ("Kennel", "A dog splitting open in the middle of the night.", "Burn it", "Brave.", "Cage it", "Smart."),
    ("Blair's Computer", "Probability of infection: high.", "Believe him", "Wise.", "Doubt him", "Pride."),
    ("Lockdown", "Garry hands over command to a thinking man.", "Take it", "Brave.", "Defer", "Polite."),
    ("Bennings", "A doppelganger caught mid-replication on a snowy slope.", "Burn him", "Hard.", "Hesitate", "Honest."),
    ("Blair's Cabin", "He smashes the radio and the dogs.", "Sedate him", "Wise.", "Lock him outside", "Cold."),
    ("Blood Cabinet", "Vials in a fridge, all slashed open in the night.", "Trust no one", "Discipline.", "Trust someone", "Heart."),
    ("Norris's Heart", "A defibrillator and a chest that opens like a mouth.", "Drop the paddles", "Brave.", "Burn him", "Final."),
    ("Head Walks", "A severed head growing legs across the floor.", "Burn it", "Final.", "Stamp it", "Reckless."),
    ("MacReady on Tape", "If I don't make it, nobody listen to anybody but the people you've seen with me in this room.", "Record it", "Honest.", "Skip the tape", "Cautious."),
    ("Blood Test", "Hot wire from a flame in a Petri dish.", "Test everyone", "Discipline.", "Test only suspects", "Wise."),
    ("Palmer Jumps", "A scream of skin, a flame burst, a window broken.", "Cover the door", "Smart.", "Run", "Smart."),
    ("Generator Out", "Heating units dropping, frostbite climbing.", "Restart it", "Brave.", "Burn the rest of the camp", "Final."),
    ("Underground Saucer", "An excavation, ice melted, a craft beneath the snow.", "Wire the explosives", "Final.", "Climb in", "Reckless."),
    ("Blair Returns", "He has been changing, has been digging, has been building.", "Confront him", "Brave.", "Wait for him to come out", "Wise."),
    ("Dynamite Down", "Charges in the ice over the saucer.", "Set the timer", "Final.", "Run", "Smart."),
    ("Explosions", "Walls of snow and ice rising and falling.", "Crawl out", "Brave.", "Hold the line", "Honest."),
    ("Two Men in the Snow", "A bottle of scotch, a fire, a long silence in the wind.", "Drink", "Honest.", "Wait", "Patient."),
], [
    ("end_fire", "Wait for the Cold", "You sit across from Childs with a flask between you and you watch each other for tells while the fire dies, and you wait for the dawn or the end."),
    ("end_blood", "Test Passed", "You both come up clean. The next research team finds you sleeping back-to-back in the wreckage."),
    ("end_chase", "The Thing Walks", "One of you is wrong. The other one doesn't know it yet. The wind takes the bottle. The story does not end."),
])

FM_GET_OUT = linear_story({
    "id": "fm-get-out",
    "title": "The Sunken Place",
    "sourceTitle": "Get Out",
    "kind": "movie",
    "synopsis": "A photographer meets his girlfriend's family, a kitchen full of help, a teacup that puts him through the floor, and a basement with a slide projector.",
    "releaseYear": 2017, "addedAt": ADDED, "genre": "Horror",
    "tags": ["peele", "social", "hypnosis", "twist"], "rating": 5, "loved": True,
}, [
    ("Packing", "A small bag, a kiss, a question about whether her parents know you are Black.", "Ask", "Honest.", "Skip it", "Polite."),
    ("Deer on the Road", "An impact, a state trooper at the window.", "Show your license", "Wise.", "Refuse politely", "Brave."),
    ("Armitage House", "A long drive, white columns, two staff members who do not blink right.", "Be friendly", "Polite.", "Be wary", "Honest."),
    ("Dad's Tour", "Photos of grandparents, a fencing trophy, a knowing wink.", "Smile", "Polite.", "Probe", "Brave."),
    ("Georgina", "The housekeeper pours sweet tea with a smile pinned on.", "Help her", "Heart.", "Step back", "Polite."),
    ("Walter", "The groundskeeper runs full speed at you in the dark.", "Greet him", "Brave.", "Step aside", "Smart."),
    ("Missy's Stir", "A teaspoon against porcelain in a small dark room.", "Resist", "Brave.", "Talk", "Honest."),
    ("The Sunken Place", "A long fall into a dark with your own crying face in the corner.", "Climb", "Brave.", "Sink", "Tired."),
    ("Morning", "A cigarette forgotten by you for years.", "Confront Missy", "Brave.", "Pretend nothing happened", "Cowardly."),
    ("The Party", "A lawn full of bidders pretending to be friends.", "Mingle", "Polite.", "Stay close to Rose", "Heart."),
    ("Logan", "A familiar face, much older inside.", "Ask about Brooklyn", "Brave.", "Move on", "Polite."),
    ("Flash Photo", "Logan's nose bleeds, his eyes snap, his mouth opens.", "Get out", "Brave.", "Reassure him", "Polite."),
    ("Rod on the Phone", "TSA. He believes you immediately.", "Tell him everything", "Honest.", "Be vague", "Cowardly."),
    ("Rose's Box", "Photographs of past Black partners she pretended you were the first.", "Bolt", "Brave.", "Confront her", "Brave."),
    ("Teacup", "Missy on the couch tapping ceramic.", "Pocket cotton", "Cunning.", "Run", "Smart."),
    ("Basement Operation", "A patient strapped in a chair and a doctor with a smile.", "Wait for the moment", "Patient.", "Burst out", "Reckless."),
    ("Petrified Cotton", "Earbuds of fluff stop the trance.", "Stay limp", "Cunning.", "Snap up", "Brave."),
    ("Jeremy at the Door", "Lacrosse stick and a leer.", "Drop the boule", "Smart.", "Talk", "Honest."),
    ("Rose with a Rifle", "She is on the porch with grandma's body knocking on a window.", "Take her keys", "Brave.", "Get past her", "Smart."),
    ("Walter Wakes", "A flash, a sentence in his real voice, a gun handed back.", "Trust him", "Mercy.", "Stay back", "Wise."),
    ("Headlights", "Sirens. A friend in a TSA jacket at the wheel.", "Get in", "Brave.", "Wave", "Tired."),
], [
    ("end_rod", "TSA on the Scene", "Rod pulls up in a white SUV and you get in and the gates close behind you and the house goes silent for the first time in a hundred years."),
    ("end_burn", "Burn It Down", "You drag a candle through the parlor and the photographs flutter and the house lights up against a cold sky, and the lawn fills with confused neighbors."),
    ("end_walter", "Walter Salutes", "Walter, with the gun, salutes you once and turns it on the patriarch in the doorway. You drive away from a porch that has, finally, stopped smiling."),
])

FM_HEREDITARY = linear_story({
    "id": "fm-hereditary",
    "title": "The Mother's Birthday",
    "sourceTitle": "Hereditary",
    "kind": "movie",
    "synopsis": "A funeral, a treehouse, a model maker's studio, and a family that finally finds out what grandmother actually believed.",
    "releaseYear": 2018, "addedAt": ADDED, "genre": "Horror",
    "tags": ["a24", "family", "cult", "grief"], "rating": 5, "loved": True,
}, [
    ("Eulogy", "A microphone, a sister in a coffin, a son who refuses to come down.", "Speak", "Honest.", "Don't", "Cold."),
    ("Studio", "A miniature of your own house with a small version of you in it.", "Work", "Discipline.", "Stop", "Honest."),
    ("Charlie's Room", "A small girl with a tongue-click and a chocolate bar.", "Hold her", "Heart.", "Stay back", "Cold."),
    ("Party", "A teen invitation, a sister tagging along because mother insists.", "Send Peter", "Practical.", "Refuse", "Wise."),
    ("Allergic Reaction", "A nut in a cake, a swelling throat, a long drive.", "Window down", "Brave.", "Speed", "Reckless."),
    ("Tree on the Road", "An impact in the back seat that takes a daughter and a head.", "Drive home", "Cold.", "Call the police", "Honest."),
    ("Kitchen Morning", "A scream that does not stop for a day.", "Hold your son", "Heart.", "Lock the door", "Cold."),
    ("Annie at the Group", "A folding chair, a confession to strangers, a woman named Joan who knows.", "Confide more", "Honest.", "Leave", "Wise."),
    ("Joan's Apartment", "A séance, a pencil, a name said into a candle.", "Speak Charlie's name", "Reckless.", "Refuse", "Wise."),
    ("Drawings on the Wall", "A figure with a smile that is not a smile.", "Take them down", "Care.", "Photograph them", "Curious."),
    ("Sketchbook", "Annie's open notebook with a strange figure in every page.", "Burn it", "Brave.", "Tear out pages", "Compromise."),
    ("Peter's Dream", "A vision of his mother on the ceiling.", "Wake him", "Heart.", "Let him sleep", "Wise."),
    ("Grandma's Trunk", "Books bound in leather and a circle of names.", "Read", "Curious.", "Lock the lid", "Wise."),
    ("Photograph in the Album", "Grandma at a meeting of robed strangers.", "Show Steve", "Honest.", "Hide it", "Wise."),
    ("Joan in the Driveway", "A small parcel, a Praise Paimon, a smile.", "Refuse it", "Brave.", "Accept", "Tempted."),
    ("Burning the Sketchbook", "A page in the fire, a wrist in flames at the same moment on another hand.", "Drop it", "Wise.", "Burn it all", "Final."),
    ("Steve in the Living Room", "A husband on a couch with a teacup of coffee.", "Beg him to listen", "Honest.", "Stop the fire", "Wise."),
    ("Father's Door", "Steve catches fire in his chair as the sketchbook does.", "Run", "Smart.", "Try to help", "Brave."),
    ("Attic Light", "A trapdoor open at the top of the stairs and a humming above.", "Climb", "Brave.", "Lock it from below", "Wise."),
    ("Bodies in the Attic", "Headless figures in a circle and a head on a pedestal in candlelight.", "Smash the lamps", "Brave.", "Run", "Smart."),
    ("Peter, At the Window", "A whisper through the casement.", "Jump", "Tired.", "Hide", "Brave."),
], [
    ("end_treehouse", "The Treehouse Lit", "A crown is set on Peter's head by hands that are not human. The cult bows. The lights of the treehouse glow yellow against a dark hill."),
    ("end_burn", "Burn the House", "You set the studio alight at the right second and the figures inside dissolve into the photographs you spent your career building."),
    ("end_run", "A Long Drive", "You take Peter in the truck and you do not stop driving. The country opens. The treehouse light recedes. The dread does not leave the rearview."),
])

FM_JAWS = linear_story({
    "id": "fm-jaws",
    "title": "Bigger Boat",
    "sourceTitle": "Jaws",
    "kind": "movie",
    "synopsis": "A beach town, a Fourth of July, a chief who hates water, and a great white shark with a long memory.",
    "releaseYear": 1975, "addedAt": ADDED, "genre": "Horror",
    "tags": ["spielberg", "creature", "summer", "boat"], "rating": 5, "loved": True,
}, [
    ("First Swim", "A girl swims out from a bonfire on a beach.", "Track her flashlight", "Brave.", "Wait at the fire", "Cautious."),
    ("Mayor's Office", "Vaughn wants the beaches open for the Fourth.", "Refuse", "Brave.", "Compromise", "Wise."),
    ("Coroner's Report", "Probable shark, edited later to boat accident.", "Document the original", "Honest.", "Sign the edit", "Cowardly."),
    ("Boy on a Raft", "A scream, a yellow line dragged under, a mother on the sand.", "Help her", "Heart.", "Clear the beach", "Discipline."),
    ("Town Hall", "Quint scratches a fingernail across a chalkboard.", "Listen", "Honest.", "Brush him off", "Polite."),
    ("Hooper Arrives", "An oceanographer with a long beard and a checklist.", "Trust him", "Wise.", "Hesitate", "Cautious."),
    ("Tiger Shark Tied to the Dock", "The mayor wants the photograph.", "Cut it open", "Brave.", "Skip the autopsy", "Polite."),
    ("Night Dive", "A wrecked boat, a tooth in the hull, a dead fisherman's head.", "Surface fast", "Smart.", "Hold the tooth", "Brave."),
    ("Fourth of July", "Beach packed, kid in a black wetsuit pranking, a real fin in the pond.", "Clear the water", "Brave.", "Trust the patrol", "Cautious."),
    ("Estuary", "Michael in a sailboat with a shark below it.", "Pull him in", "Heart.", "Yell", "Honest."),
    ("Quint's Boat", "The Orca at the dock, smaller than you remembered.", "Step on", "Brave.", "Hesitate", "Honest."),
    ("Chum Line", "A bucket of guts on a slow trawl.", "Talk", "Honest.", "Stay quiet", "Tired."),
    ("First Sight", "A snout, a row of teeth, a deck that suddenly feels small.", "Tag the barrel", "Smart.", "Reach for the M1", "Reckless."),
    ("Scars", "Quint and Hooper compare wounds and laugh.", "Show yours", "Honest.", "Tell yours", "Heart."),
    ("Indianapolis Speech", "Quint with whiskey, a story about a sinking ship.", "Listen", "Honor.", "Pour another", "Friend."),
    ("Shark Tested", "It pulls the boat backward by its barrels.", "Cut the line", "Wise.", "Hold on", "Stubborn."),
    ("Engine Trouble", "Pistons screaming and a captain laughing too loud.", "Slow down", "Wise.", "Push harder", "Reckless."),
    ("Cage", "Hooper in a steel box and a shark with a snout it can fit anywhere.", "Lower him", "Brave.", "Wait", "Cautious."),
    ("Stern Crashing", "A jaw on the transom and a man sliding down the deck.", "Grab Quint's leg", "Brave.", "Hold the rail", "Smart."),
    ("Compressed Air Tank", "A yellow tank rolling around the deck.", "Throw it in", "Brave.", "Shoot at it now", "Reckless."),
    ("Mast Top", "A man with a rifle and a sentence about a smile.", "Aim true", "Brave.", "Pull the trigger now", "Reckless."),
], [
    ("end_smile", "Smile You", "The tank explodes and the shark goes red and the chief, who hates the water, paddles back to shore on debris with a friend at his side."),
    ("end_quint", "Quint's Wake", "You bury Quint at sea and you do not, in your old age, talk about him to anyone, because the right words do not exist for a man who liked sharks more than he liked people."),
    ("end_swim", "The Mayor Resigns", "Vaughn loses his job and the beach is closed for a season and the town rebuilds, this time with a new sign at the dock that says read the water."),
])

FM_ROSEMARYS_BABY = linear_story({
    "id": "fm-rosemarys-baby",
    "title": "The Bramford",
    "sourceTitle": "Rosemary's Baby",
    "kind": "movie",
    "synopsis": "A new apartment in an old building, neighbors who help too much, a tannis root necklace, and a husband who has been making promises behind a wall.",
    "releaseYear": 1968, "addedAt": ADDED, "genre": "Horror",
    "tags": ["polanski", "cult", "pregnancy", "satan"], "rating": 5, "loved": True,
}, [
    ("Apartment Tour", "Bramford. High ceilings. A secretary cabinet shoved in front of a closet.", "Take the place", "Brave.", "Pass", "Wise."),
    ("Hutch", "An old friend warns you about the building's history.", "Listen", "Wise.", "Laugh", "Polite."),
    ("Closet", "Behind the cabinet, a door, a smell, a board with a name on it.", "Investigate", "Curious.", "Push it back", "Wise."),
    ("Terry Downstairs", "A young woman in the laundry room with a tannis root pendant.", "Befriend her", "Heart.", "Be polite", "Polite."),
    ("Sidewalk Cement", "Terry's body in a pool of blood under the awning.", "Stay with her", "Honest.", "Walk on", "Cold."),
    ("Minnie and Roman", "Neighbors arrive with chocolate mousse and a thousand questions.", "Indulge them", "Polite.", "Decline", "Wise."),
    ("Mousse", "A bitter aftertaste in a spoon.", "Eat anyway", "Polite.", "Tip it in the napkin", "Wise."),
    ("Conception Night", "A dream that is not quite a dream, scratches on your thigh.", "Tell Guy", "Honest.", "Stay quiet", "Cowardly."),
    ("Pregnancy", "Sharp pains, a witchdoctor's herbal smoothie, a friendly woman insisting.", "Drink it", "Polite.", "Pour it out", "Wise."),
    ("Hutch's Hat", "A friend slips into a coma. A book about witches he tried to bring you.", "Read it", "Brave.", "Hide it", "Wise."),
    ("Sapirstein", "A doctor recommended by Minnie who dismisses every symptom.", "Trust him", "Cowardly.", "Doubt", "Wise."),
    ("Hill", "A second doctor with a kind face who lets the others in the room.", "Confide", "Brave.", "Stay vague", "Wise."),
    ("Phone Booth", "A list of clues in your pocket and a friend on the other end.", "Make the call", "Brave.", "Hang up", "Cowardly."),
    ("Anagram", "All of Them Witches. A doctor's name rearranged.", "Believe it", "Brave.", "Doubt", "Cowardly."),
    ("Friend at the Apartment", "A doctor you trust enough to come in.", "Let him in", "Brave.", "Cancel", "Cowardly."),
    ("Roman at the Door", "Friendly. Calm. Already inside.", "Run", "Brave.", "Sit", "Tired."),
    ("Labor", "Sedation, voices, a baby's cry far away.", "Resist", "Brave.", "Surrender", "Tired."),
    ("Empty Room", "A nurse with a story about a baby who did not make it.", "Ask to see", "Brave.", "Believe", "Tired."),
    ("Secret Door", "Behind the cabinet again, a black bassinet, a chant.", "Walk in", "Brave.", "Run", "Smart."),
    ("Inverted Cross", "A rocking cradle, a small wide-eyed child, an upside-down crucifix above.", "Lift the knife", "Brave.", "Drop the knife", "Tired."),
    ("Hush, Little Andy", "A circle of strangers waiting for a mother's verdict.", "Rock him", "Heart.", "Walk out", "Brave."),
], [
    ("end_rock", "Hush", "You sit by the cradle and you decide what to be his mother of. The strangers exchange a glance. It is, surprisingly, your house now."),
    ("end_walk", "Bramford Doors", "You wrap a coat around the bassinet and walk out into Central Park West. The cult does not stop you. They never could."),
    ("end_call", "The Right Doctor", "Hill comes himself this time, with two policemen and an ambulance. The cult scatters. You spend a decade telling the story to people who do not believe you."),
])

FM_EXORCIST = linear_story({
    "id": "fm-exorcist",
    "title": "Regan",
    "sourceTitle": "The Exorcist",
    "kind": "movie",
    "synopsis": "A movie-star mother in Georgetown, a small daughter who plays with a board, a priest who is losing his faith, and a long staircase outside a bedroom window.",
    "releaseYear": 1973, "addedAt": ADDED, "genre": "Horror",
    "tags": ["catholic", "possession", "priest", "georgetown"], "rating": 5, "loved": True,
}, [
    ("Iraq", "Father Merrin at a dig with a small figurine he recognizes.", "Lift it slowly", "Wise.", "Bag it", "Discipline."),
    ("Bedroom Window", "A draft in a girl's bedroom in Georgetown.", "Close the window", "Care.", "Leave it", "Tired."),
    ("Ouija Captain", "Regan tells her mother about her friend Captain Howdy.", "Worry", "Honest.", "Smile", "Polite."),
    ("Stairs Outside", "M Street's long flight at the end of an alley.", "Pass", "Wise.", "Stop and look up", "Curious."),
    ("Karras Mother", "An old woman in a hospital and a guilty son.", "Visit", "Honor.", "Skip a Sunday", "Cowardly."),
    ("Burke at the Party", "A drunken director, a piano, a small girl who urinates on the rug.", "Excuse her", "Polite.", "Hide her", "Honest."),
    ("Doctors", "Tests, lumbar punctures, a list of diagnoses that explain nothing.", "Persist", "Brave.", "Accept", "Tired."),
    ("Burke Falls", "A neck broken at the bottom of the stairs outside.", "Look up at the bedroom", "Brave.", "Look away", "Cowardly."),
    ("Detective Kinderman", "A friendly cop who wants to know about a window.", "Tell him", "Honest.", "Be vague", "Cowardly."),
    ("Bed in the Air", "The mattress rises three feet under a body wracked with seizures.", "Hold her hand", "Heart.", "Step back", "Cowardly."),
    ("Crucifix", "A small object found under a pillow with a use you do not want to imagine.", "Take it away", "Brave.", "Leave it", "Tired."),
    ("Recordings", "Regan's voice on a tape played backwards.", "Listen", "Brave.", "Stop", "Tired."),
    ("Karras at the Door", "A priest in a black coat at the threshold.", "Welcome him", "Hope.", "Beg him", "Honest."),
    ("Holy Water", "Tap, blessed, in a Coke bottle that scalds.", "Note it", "Wise.", "Spray more", "Reckless."),
    ("Mother's Picture", "Pa-zu-zu spelled out on a blistered belly.", "Photograph it", "Honest.", "Hide it", "Cowardly."),
    ("Merrin Arrives", "A small old priest with a black bag on the doorstep.", "Defer to him", "Wise.", "Brief him", "Discipline."),
    ("Stair to the Bedroom", "Two priests and a rite and a door.", "Knock", "Brave.", "Push", "Discipline."),
    ("The Power of Christ", "A chant, a thrash, a window cracking inward.", "Don't stop", "Brave.", "Pause", "Wise."),
    ("Merrin's Heart", "An old priest on a rug with a hand to his chest.", "Continue alone", "Brave.", "Pray for help", "Honest."),
    ("Karras Offers", "Come into me, he says, with a fist.", "Speak", "Final.", "Hold him back", "Care."),
    ("Window", "A long fall down to M Street.", "Push", "Final.", "Wait", "Honest."),
], [
    ("end_calm", "Regan, Calm", "She wakes in the morning with no memory of any of it and an interest in a kind man's collar she finds in the rug."),
    ("end_priest", "Karras at the Bottom", "The neighborhood priest gives him last rites on a wet stair and a city wakes to a small story buried inside its larger one."),
    ("end_dig", "Pazuzu in the Sand", "Merrin's small figurine is buried again outside Mosul, and the wind passes over it, and the world is, for one summer, quieter."),
])

FM_LET_RIGHT_ONE_IN = linear_story({
    "id": "fm-let-the-right-one-in",
    "title": "Eli and Oskar",
    "sourceTitle": "Let the Right One In",
    "kind": "movie",
    "synopsis": "A bullied boy in a Stockholm suburb, a girl who only comes out at night, a pool, and an invitation that has to be spoken aloud.",
    "releaseYear": 2008, "addedAt": ADDED, "genre": "Horror",
    "tags": ["vampire", "swedish", "snow", "first-love"], "rating": 5, "loved": True,
}, [
    ("Snow on a Knife", "Practice stabbing a tree at midnight in your underwear.", "Practice", "Lonely.", "Go inside", "Wise."),
    ("Eli on the Jungle Gym", "A pale girl, barefoot in the snow, who tells you she cannot be your friend.", "Speak to her", "Brave.", "Walk past", "Wise."),
    ("Pool", "Conny grabs your ear at the edge of the pool with a switch.", "Fight back", "Brave.", "Endure", "Tired."),
    ("Hakan's Errand", "An old man hangs a child upside down in a forest with a funnel.", "Watch", "Honest.", "Walk away", "Wise."),
    ("Cube Game", "Eli solves a Rubik's cube overnight under your window.", "Be impressed", "Heart.", "Be wary", "Cautious."),
    ("Invitation Test", "Come in, you say. She steps inside, and she begins to bleed.", "Pull her in", "Heart.", "Say it", "Brave."),
    ("Sleeping in Your Bed", "She is cold, you are warm, the door is locked.", "Hold her hand", "Heart.", "Sleep apart", "Polite."),
    ("Hakan's Hospital", "He goes to the window for her at dawn, with a smile.", "Stay with him", "Mercy.", "Step back", "Honest."),
    ("Lake Body", "A drained corpse and a town that is starting to notice.", "Tell the police", "Honest.", "Stay quiet", "Loyal."),
    ("Virginia at the Window", "A cat-laden apartment with a friend who is now afraid of sunlight.", "Help her", "Heart.", "Run", "Smart."),
    ("Curtains Open", "She asks for the curtains.", "Open them", "Mercy.", "Refuse", "Cold."),
    ("Eli at Your Door", "A whisper, an invitation already spoken, a kiss on the cheek.", "Hold her", "Heart.", "Step back", "Cautious."),
    ("Conny's Brother", "A bigger boy with a bigger grudge.", "Stand up", "Brave.", "Run", "Smart."),
    ("Pool, Again", "Conny holds your head under water and counts.", "Hold your breath", "Brave.", "Surrender", "Tired."),
    ("Splash", "A head and a hand fall on the pool deck above you.", "Open your eyes", "Brave.", "Stay closed", "Tired."),
    ("Eli on the Edge", "She lifts you out of the water with a small, kind smile.", "Take her hand", "Heart.", "Look away", "Cold."),
    ("Train Station", "A small box on the seat across from you on a long train south.", "Tap", "Heart.", "Look out the window", "Honest."),
    ("Morse Tap", "A small reply from the box.", "Tap back", "Heart.", "Stay quiet", "Polite."),
    ("Dawn Outside", "Sun across a pine forest as the train rocks.", "Cover the box", "Care.", "Open the window", "Reckless."),
    ("Conductor Walks Past", "Tickets and small change.", "Stay still", "Cunning.", "Hold the box tight", "Care."),
    ("Empty Carriage", "Just the two of you and the morse going.", "Sleep", "Heart.", "Watch the snow", "Honest."),
], [
    ("end_train", "Puss, Puss", "You and the box ride south for days, and the small tapping never stops, and the snow goes from white to gray to slush as the train carries you somewhere kinder."),
    ("end_pool", "On the Tile", "You climb out of the pool and Eli pulls a towel around you, and the two of you walk past a half-dozen severed surprises with an even smaller smile."),
    ("end_letter", "A Letter Home", "Decades later you write your mother a postcard from a city she cannot name, and you sign it with a small symbol Eli taught you that means thank you for the invitation."),
])

FM_NIGHT_OF_LIVING_DEAD = linear_story({
    "id": "fm-night-of-living-dead",
    "title": "They're Coming to Get You",
    "sourceTitle": "Night of the Living Dead",
    "kind": "movie",
    "synopsis": "A cemetery, a farmhouse, a basement argument, and a country radio voice that is finally telling the truth.",
    "releaseYear": 1968, "addedAt": ADDED, "genre": "Horror",
    "tags": ["romero", "zombie", "siege", "blackandwhite"], "rating": 5, "loved": True,
}, [
    ("Cemetery", "A brother teases his sister at a headstone.", "Tease back", "Light.", "Stay quiet", "Honest."),
    ("First Walker", "A pale figure stumbles between the stones.", "Approach", "Reckless.", "Run", "Smart."),
    ("Brother Falls", "A head hits a marker with a sound that does not stop.", "Drive away", "Smart.", "Wait for him", "Loyal."),
    ("Farmhouse", "A house at the end of a dirt road with a porch screen torn.", "Inside", "Brave.", "Hide outside", "Cautious."),
    ("Ben Arrives", "A man with a tire iron and a calm voice.", "Trust him", "Wise.", "Stay cautious", "Wary."),
    ("Boards on Windows", "Hammer, nails, a kitchen drawer of supplies.", "Help him", "Discipline.", "Hide upstairs", "Cowardly."),
    ("Cellar Door", "A man named Cooper shouts up from the basement.", "Speak through it", "Polite.", "Lock it from above", "Hard."),
    ("Radio", "A bulletin about reanimated corpses in three states.", "Listen carefully", "Wise.", "Switch it off", "Cowardly."),
    ("Karen", "A small girl in a corner, hurt, fevered, quiet.", "Tend her", "Heart.", "Stay back", "Wise."),
    ("Cooper's Strategy", "Lock everyone in the cellar and ride it out.", "Refuse", "Brave.", "Compromise", "Wise."),
    ("Tom and Judy", "A young couple keen on the pickup truck out front.", "Plan it together", "Smart.", "Plan alone", "Pride."),
    ("Pump", "A long run with cans to a gas pump at the side of the yard.", "Run", "Brave.", "Send Tom", "Practical."),
    ("Spilled Gasoline", "Flame in the wrong direction.", "Throw the torch", "Brave.", "Drop it", "Honest."),
    ("Tom Burning", "A truck on fire and a body inside.", "Look away", "Mercy.", "Watch", "Honest."),
    ("Walkers at the Door", "A pile of hands on the screen.", "Light the curtains", "Final.", "Brace", "Brave."),
    ("Karen on the Stairs", "A small figure with a trowel and an appetite.", "Stop her", "Mercy.", "Run", "Smart."),
    ("Helen's Last Word", "A mother on a basement floor and a daughter with a tool.", "Try to save Helen", "Heart.", "Bar the door", "Cold."),
    ("Cooper Shoots", "A wrong moment, a wild round.", "Disarm him", "Brave.", "Wait", "Honest."),
    ("Dawn at the Window", "Voices in the field, men with dogs and rifles.", "Wave", "Hope.", "Hide", "Cautious."),
    ("Sheriff at the Treeline", "A sweep through the yard with a clear order to fire on anything moving.", "Call out", "Brave.", "Stay silent", "Cowardly."),
    ("Bedroom Window", "A shadow at the curtain and a rifleman with a steady aim.", "Step back", "Wise.", "Step forward", "Honest."),
], [
    ("end_dawn", "Posse on the Porch", "You walk down the porch with both hands up and the sheriff's man, suspicious of nothing in particular, lowers his rifle and lets you live."),
    ("end_basement", "Cellar Door Holds", "You spend the night with Cooper after all, and the radio announces the all clear at noon and a small girl on a stair never quite stops being your nightmare."),
    ("end_road", "Truck on Dirt Road", "You take the only working truck out at dawn and you do not look back, and the radio crackles and the road dust hangs and the country is, briefly, quiet."),
])

HORROR_SPECS = [FM_SHINING, FM_ALIEN, FM_THING, FM_GET_OUT, FM_HEREDITARY,
                FM_JAWS, FM_ROSEMARYS_BABY, FM_EXORCIST, FM_LET_RIGHT_ONE_IN, FM_NIGHT_OF_LIVING_DEAD]
