# Top 10 Action picks from IMDb Top 250 (skipping titles already in fm- catalog).
from stories_data import linear_story

ADDED = "2026-06-03T00:00:00Z"

FM_LOTR_RETURN = linear_story({
    "id": "fm-lotr-return",
    "title": "The Steward and the King",
    "sourceTitle": "The Lord of the Rings: The Return of the King",
    "kind": "movie",
    "synopsis": "Minas Tirith burns. Two hobbits climb Mount Doom. Every blade of grass between matters.",
    "releaseYear": 2003, "addedAt": ADDED, "genre": "Action",
    "tags": ["epic", "fantasy", "war", "fellowship"], "rating": 5, "loved": True,
}, [
    ("Beacon of Amon Din", "The signal fire is unlit and the steward forbids it.", "Light it anyway", "Defiance.", "Wait for orders", "Loyal."),
    ("Pippin's Vow", "Denethor offers a small sword and a long oath.", "Kneel and swear", "Honor.", "Hesitate", "Honest."),
    ("The Paths of the Dead", "A door in the mountain, and behind it, an army of oathbreakers.", "Enter", "Brave.", "Ride the long road", "Wise."),
    ("Faramir's Charge", "Osgiliath is lost. Denethor orders a doomed cavalry charge.", "Ride", "Duty.", "Refuse", "Honest."),
    ("Eowyn in Mail", "A young rider with hidden hair offers Merry a place at her stirrup.", "Go with her", "Heart.", "Stay behind", "Practical."),
    ("Shelob's Lair", "Sam hears Frodo scream past the webbing.", "Run in", "Loyal.", "Fetch sting first", "Smart."),
    ("The Stairs of Cirith Ungol", "Gollum whispers that the fat one stole the bread.", "Believe Gollum", "Trusting.", "Watch Gollum", "Wary."),
    ("Pyre of Denethor", "The steward calls for oil and a torch over his sleeping son.", "Tackle him", "Brave.", "Save Faramir alone", "Focused."),
    ("Horn of Rohan", "Dawn, and six thousand spears at the edge of the Pelennor.", "Charge first rank", "Glory.", "Hold flank", "Discipline."),
    ("The Witch-King", "No man can kill him, he laughs. Eowyn answers with her helm in her hand.", "Strike for the face", "Brave.", "Distract with Merry's blade", "Cunning."),
    ("Mouth of Sauron", "A herald rides out with Frodo's mithril shirt swinging from a chain.", "Believe him", "Honest.", "Refuse to break", "Hope."),
    ("Black Gate Opens", "The host of the West is a coin tossed into the dark.", "Stand at front", "Lead.", "Stand with Pippin", "Friend."),
    ("Sam Carries Him", "Frodo cannot walk. The mountain is still there.", "Carry him", "Love.", "Drag the ring alone", "Stern."),
    ("Crack of Doom", "Frodo at the edge slips the ring onto his own finger.", "Tackle him", "Desperate.", "Wait for Gollum", "Fated."),
    ("Eagles", "Wings against the smoke, far off.", "Hold on", "Hope.", "Let go", "Peace."),
    ("Fields of Cormallen", "A clearing, a banner, a song you do not yet recognize is yours.", "Stand", "Honor.", "Kneel", "Humble."),
    ("White Tree Blooming", "A sapling unfolds in the courtyard of Minas Tirith for no clear reason.", "Tend it", "Hope.", "Let it grow wild", "Trust."),
    ("Coronation", "Aragorn bows to the hobbits. The whole city follows.", "Bow back", "Equal.", "Stand straight", "Proud."),
    ("Return to the Shire", "The Green Dragon is loud with strangers who do not know your name.", "Sit at your old table", "Quiet.", "Walk past", "Changed."),
    ("Bag End", "The kettle. The book. A page left blank for someone else.", "Write your part", "Honest.", "Leave it blank", "Humble."),
    ("Grey Havens", "A ship at the quay, and Gandalf already aboard.", "Board with Frodo", "Mercy.", "Stay on the dock", "Home."),
], [
    ("end_king", "King and Steward", "You ride home to the Shire white-haired and quiet, and tend a garden that no enemy can find. The crown was Aragorn's; the long second life is yours."),
    ("end_west", "Into the West", "You board the ship, and the sea air mends what Mordor broke. Somewhere ahead, a green country."),
    ("end_quiet", "The Last Page", "You leave the book open on the table for the next small hand. The story keeps going without you, which is the proof it was good."),
])

FM_LOTR_TWO_TOWERS = linear_story({
    "id": "fm-lotr-two-towers",
    "title": "Helm's Deep",
    "sourceTitle": "The Lord of the Rings: The Two Towers",
    "kind": "movie",
    "synopsis": "A broken fellowship, a creature in the marshes, and ten thousand Uruks at the gate of an old fortress.",
    "releaseYear": 2002, "addedAt": ADDED, "genre": "Action",
    "tags": ["epic", "fantasy", "siege", "rohan"], "rating": 5, "loved": True,
}, [
    ("Emyn Muil", "A wet, gray maze of stones, and footsteps not your own behind you.", "Set a trap", "Wary.", "Press on", "Trust."),
    ("Smeagol's Bargain", "He swears on the precious to be your guide.", "Bind him", "Stern.", "Believe him", "Mercy."),
    ("The Three Hunters", "Aragorn presses his ear to the ground. Two days ahead, maybe more.", "Run", "Fierce.", "Rest first", "Wise."),
    ("Riders of Rohan", "A line of horsemen breaks over the ridge with spears down.", "Stand and speak", "Brave.", "Hide in the grass", "Smart."),
    ("Fangorn's Edge", "A forest that watches you back, breathing slowly.", "Enter", "Curious.", "Skirt it", "Cautious."),
    ("Treebeard", "An entmoot, in a voice that takes hours per word.", "Plead urgently", "Honest.", "Speak slow", "Patient."),
    ("Edoras", "The hall is dim and the king is small inside a borrowed body.", "Confront Wormtongue", "Bold.", "Win Theoden first", "Strategic."),
    ("Eowyn at the Door", "She offers a cup of water and a steady look.", "Drink", "Honor.", "Refuse the courtesy", "Cold."),
    ("Westfold Burning", "Refugees on the road, smoke on the horizon.", "Go to Helm's Deep", "Shelter.", "Ride to meet the foe", "Brave."),
    ("Warg Riders", "Ambush on the plain, and Aragorn over the cliff.", "Chase the wargs", "Fierce.", "Get the people inside", "Duty."),
    ("Glittering Caves", "The women and children file into stone that has not seen war.", "Stay with them", "Care.", "Take the wall", "Soldier."),
    ("Elven Reinforcements", "Haldir's company arrives, cloaked, silent, in the rain.", "Place them at the wall", "Trust.", "Hold them as reserve", "Wise."),
    ("Berm at the Culvert", "A weak point in the old stone, and a torch running for it.", "Loose every arrow", "Fierce.", "Save the shot", "Disciplined."),
    ("The Wall Breaks", "A blast, a hole, and ladders already on the lip.", "Hold the breach", "Brave.", "Fall back to the keep", "Smart."),
    ("Causeway", "A narrow neck of stone packed with Uruks like a fist.", "Charge them", "Glory.", "Cut the bridge", "Hard."),
    ("Aragorn at the Gate", "He proposes to ride out at dawn for one last charge.", "Ride with him", "Friend.", "Hold the hall", "Loyal."),
    ("Gandalf on the Hill", "White rider, east edge, sun behind.", "Cheer", "Hope.", "Brace ranks", "Steady."),
    ("Dead Marshes", "Faces in the water that you must not look at.", "Follow Smeagol", "Trust.", "Find your own path", "Stubborn."),
    ("Faramir's Choice", "He has the ring and a long road back to his father.", "Speak to him plainly", "Honest.", "Try to escape", "Desperate."),
    ("Osgiliath", "A Nazgul circling and Frodo at the edge of the broken bridge.", "Pull him back", "Loyal.", "Let the ring decide", "Fated."),
    ("Sam's Speech", "There's some good in this world, and it's worth fighting for.", "Believe it", "Heart.", "Walk on quietly", "Honest."),
], [
    ("end_hold", "The Hall Holds", "The hornblast at dawn is yours. You hold the keep until white riders break the line, and you sleep that night in a cold corner that feels like home."),
    ("end_ride", "Dawn Charge", "You ride with Aragorn out of the gate and into a song the Mark will sing for a thousand years. Half of you comes back. All of it matters."),
    ("end_carry", "Carrying the Carrier", "Frodo cannot, so you do. Up a long road that has no name yet, you carry the man who carries the ring, and nobody writes that part down for centuries."),
])

FM_EMPIRE_STRIKES_BACK = linear_story({
    "id": "fm-empire-strikes-back",
    "title": "I Am Your Father",
    "sourceTitle": "Star Wars: The Empire Strikes Back",
    "kind": "movie",
    "synopsis": "An ice planet, a swamp, a city in the clouds, and a sentence at the end of a long fall that you will hear forever.",
    "releaseYear": 1980, "addedAt": ADDED, "genre": "Action",
    "tags": ["space", "rebellion", "jedi", "twist"], "rating": 5, "loved": True,
}, [
    ("Hoth Patrol", "Wampa tracks in the snow, and the sun going down fast.", "Investigate", "Brave.", "Report and return", "Smart."),
    ("Echo Base Klaxon", "Probe droid spotted. The Empire is on the way.", "Evacuate first", "Care.", "Hold the line", "Soldier."),
    ("Snowspeeder Tow Cables", "Walkers on the ridge, and only one trick left.", "Try the cables", "Clever.", "Strafe the cockpits", "Direct."),
    ("Falcon Won't Start", "Imperial troops in the corridor and a hyperdrive that coughs.", "Stay and fix it", "Bold.", "Sublight escape", "Desperate."),
    ("Dagobah Approach", "Sensors lie. The swamp rises up to grab the landing skids.", "Trust the Force", "Surrender.", "Trust the panel", "Stubborn."),
    ("The Cave", "Vader's mask in your visor, and your saber already drawn.", "Drop the saber", "Wise.", "Fight him", "Reckless."),
    ("Lift the X-Wing", "Yoda says size matters not. The marsh disagrees.", "Try", "Hope.", "Walk away", "Doubt."),
    ("Asteroid Field", "Never tell you the odds. The cockpit goes dark for a second.", "Dive deeper", "Brave.", "Climb out", "Cautious."),
    ("Space Slug", "A cave that breathes. The stars at its mouth like teeth.", "Boost full", "Quick.", "Drift quiet", "Stealth."),
    ("Bounty Hunters", "A line of them on a Star Destroyer deck. One in green Mandalorian plate.", "Hide on the hull", "Cunning.", "Run sublight", "Brave."),
    ("Cloud City Welcome", "Lando smiles too wide and the dinner doors slide open on Vader at the head of the table.", "Draw", "Quick.", "Drop the blaster", "Smart."),
    ("Carbon Freeze", "Han goes first, and Leia holds his face.", "Say it", "Heart.", "Don't say it", "Stoic."),
    ("Tunnels of Cloud City", "Lando whispers there is a way out for the others, if you trust him now.", "Trust him", "Mercy.", "Refuse", "Wary."),
    ("Saber Duel", "Vader is patient and you are not. Sparks on a catwalk over nothing.", "Press the attack", "Brave.", "Defend", "Wise."),
    ("Carbonite Slab", "Boba Fett's prize lifted onto a transport while you bleed in a corridor.", "Pursue Fett", "Loyal.", "Pursue Vader", "Duty."),
    ("Gantry Over the Reactor", "A hand cut. A truth offered. A long fall to nothing.", "Take his hand", "Tempted.", "Let go", "True."),
    ("Falcon Sweeps Under", "Lando at the controls, Leia at the cockpit, a voice in your mind saying her name.", "Call her", "Hope.", "Stay still", "Spent."),
    ("Hyperdrive Sabotaged", "It is fixed by a fussy gold droid pieced back together in a sack.", "Trust it", "Faith.", "Limp on sublight", "Practical."),
    ("Rebel Fleet, Quiet", "Medical frigate, new hand, old face in the window.", "Touch the glass", "Honest.", "Turn away", "Hard."),
    ("Lando's Vow", "He will find Han or he will die trying.", "Believe him", "Hope.", "Go yourself", "Stubborn."),
    ("Stars Again", "The galaxy is wider and worse than yesterday, and you are still in it.", "Take the next mission", "Soldier.", "Sit a moment", "Honest."),
], [
    ("end_train", "Back to Dagobah", "You return to the swamp to finish what you started, and Yoda is shorter and stranger and entirely correct, again."),
    ("end_chase", "The Hunt for Fett", "You and Lando burn a hundred contacts and a half a dozen ships looking for one slab of carbonite across a galaxy that does not want it found."),
    ("end_quiet", "A New Hand", "You learn to live with the new hand, and with the sentence, and you do not lie down. That is the lesson the Empire never expected anyone to learn."),
])

FM_GLADIATOR = linear_story({
    "id": "fm-gladiator",
    "title": "Are You Not Entertained",
    "sourceTitle": "Gladiator",
    "kind": "movie",
    "synopsis": "A general becomes a slave, becomes a gladiator, becomes the thing that an emperor cannot kill quietly.",
    "releaseYear": 2000, "addedAt": ADDED, "genre": "Action",
    "tags": ["rome", "revenge", "arena", "loyalty"], "rating": 5, "loved": True,
}, [
    ("Germania, Dawn", "Wheat in your fingers, and a German emissary's head in the snow.", "Send a final offer", "Mercy.", "Order the catapults", "Soldier."),
    ("Aurelius' Tent", "The old emperor offers you Rome until his son returns.", "Accept the burden", "Duty.", "Ask to go home", "Honest."),
    ("Commodus", "He embraces his father a little too long. His father does not breathe again.", "Confront him", "Bold.", "Bide your time", "Wise."),
    ("Praetorians at Dawn", "Soldiers loyal to a name you do not say. Your wife and son already two days ahead.", "Fight", "Brave.", "Ride", "Desperate."),
    ("The Farmhouse Burning", "You arrive too late and the world ends in a doorway.", "Bury them", "Honest.", "Ride after the killers", "Reckless."),
    ("Proximo's Yard", "A trader in Zucchabar buys you cheap and feeds you better.", "Train hard", "Discipline.", "Refuse to perform", "Stubborn."),
    ("First Sand", "A circle of dirt and a man with a curved sword who wants your life.", "End it quickly", "Hard.", "Show the crowd", "Cunning."),
    ("Juba", "A Numidian asleep with a wooden carving of his daughter on his chest.", "Speak", "Friend.", "Sleep", "Quiet."),
    ("To Rome", "Proximo says the only way to the emperor is the Colosseum.", "Go willingly", "Strategic.", "Refuse", "Honest."),
    ("Carthage Reenactment", "Chariots, archers, and a script that wants you dead in act one.", "Stand alone", "Brave.", "Form a wall", "Discipline."),
    ("Are You Not Entertained", "Crowd silent. Sword raised. Eyes on the emperor's box.", "Throw the sword", "Defiant.", "Bow", "Strategic."),
    ("My Name Is Maximus", "Helm off. Names listed. An emperor learns whose face he has been watching.", "Speak the names", "Honest.", "Refuse to bow", "Pride."),
    ("Lucilla", "She slips into your cell with a plan and a small hand on yours.", "Trust her", "Hope.", "Refuse the plot", "Cautious."),
    ("The Senator's Plan", "Gracchus would have you slip from Rome to your army at Ostia.", "Agree", "Hope.", "Stay for the boy", "Heart."),
    ("Lucius", "The little prince calls you Maximus the Hero. Commodus watches from a doorway.", "Be kind", "Heart.", "Be cold", "Smart."),
    ("Tigris of Gaul", "Tigers from trapdoors. A retired champion across the sand.", "Spare him", "Honor.", "Finish him", "Hard."),
    ("The Escape", "A long tunnel under the city, and someone has betrayed it already.", "Press on", "Brave.", "Turn back to the others", "Loyal."),
    ("Proximo at the Gate", "He buys you a minute with his own life and a Spanish sword.", "Take it", "Honor.", "Stay with him", "Loyal."),
    ("Lucilla Caught", "Commodus has the boy at the end of a knife on her shoulder.", "Surrender", "Care.", "Refuse and fight", "Hard."),
    ("Knife in the Side", "Commodus slips the wound under your armor before the duel begins.", "Hide it", "Stoic.", "Let the crowd see", "Honest."),
    ("The Last Sand", "A hundred thousand silent Romans, and a brother who does not understand he has lost.", "Strike clean", "Justice.", "Drop the sword", "Mercy."),
], [
    ("end_home", "Wheat in the Sun", "You walk through the long grass toward a door you remember. The latch lifts. Someone calls your name in the voice that was always home."),
    ("end_rome", "A Senator's Rome", "Gracchus carries your body out and the people carry the rest. The Republic, for a season, almost works."),
    ("end_name", "Strength and Honor", "Juba buries the small wooden figures in the sand and stands. We will see you again, he says. But not yet. Not yet."),
])

FM_INGLOURIOUS = linear_story({
    "id": "fm-inglourious-basterds",
    "title": "The Basterds in the Cinema",
    "sourceTitle": "Inglourious Basterds",
    "kind": "movie",
    "synopsis": "A Jewish theater owner, a squad of avenging soldiers, and a Nazi premiere with a very flammable nitrate reel.",
    "releaseYear": 2009, "addedAt": ADDED, "genre": "Action",
    "tags": ["war", "revenge", "cinema", "tarantino"], "rating": 5, "loved": True,
}, [
    ("LaPadite's Farm", "Landa drinks a glass of milk and asks polite questions in four languages.", "Lie", "Brave.", "Tell the truth", "Doomed."),
    ("Under the Floor", "Floorboards above and a girl in the dark holding her breath.", "Run for the woods", "Reckless.", "Stay still", "Patient."),
    ("Shosanna in Paris", "Years later, a cinema marquee with your new name above the door.", "Burn it down", "Vengeance.", "Keep it open", "Hope."),
    ("Aldo's Speech", "Each man, one hundred Nazi scalps.", "Take the oath", "Brave.", "Stay quiet", "Honest."),
    ("Stiglitz Joins", "A German sergeant in a cell with a list of dead officers.", "Recruit him", "Smart.", "Leave him", "Cautious."),
    ("Zoller", "A young hero won't stop asking about your cinema.", "Be cold", "Wise.", "Play along", "Strategic."),
    ("Goebbels' Invitation", "Lunch with the Reich's propaganda minister and a strudel and cream.", "Eat the strudel", "Cool.", "Refuse politely", "Wary."),
    ("La Louisiane", "A basement tavern, the wrong dialect, and an SS officer with a kind smile.", "Walk out slow", "Smart.", "Bluff it", "Brave."),
    ("Three Fingers", "He orders three glasses with the wrong hand. The room goes still.", "Draw", "Quick.", "Talk", "Doomed."),
    ("Bridget Beneath the Table", "A wounded English spy among dead Germans and a smell of gunpowder.", "Get her out", "Loyal.", "Leave her", "Cold."),
    ("Splice Room", "Marcel hands you cans of nitrate film, a hundred years of flammable history.", "Stack them by the screen", "Hard.", "Spread them in the aisles", "Vengeful."),
    ("Premiere Arrivals", "Limousines, flashbulbs, the high boots of the Reich, the wrong shoe size.", "Smile big", "Brave.", "Limp inside", "Doomed."),
    ("Landa's Strudel", "He orders for you and watches the cream sink into the pastry.", "Eat", "Cool.", "Push it away", "Cold."),
    ("Champagne in the Lobby", "A waiter you trained yourself, and a tray with a small folded note under the glass.", "Pass the note", "Smart.", "Hold it", "Cautious."),
    ("Box Seat", "Hitler laughing at his own image on a screen you control.", "Lock the doors", "Final.", "Wait for the reel", "Patient."),
    ("Marcel at the Curtain", "Cigarette. Match. The whole back wall of the auditorium drenched in cellulose.", "Light it", "Vengeance.", "Wait one more minute", "Final."),
    ("Donny Behind the Box", "A baseball bat and a long-cherished list of names.", "Open fire", "Direct.", "Let the fire do it", "Patient."),
    ("Zoller in the Booth", "He has followed you up and he is bleeding and he is not done.", "Shoot first", "Hard.", "Hesitate", "Honest."),
    ("Aldo Captured", "Landa offers a deal: a Medal of Honor and a house on Nantucket.", "Sign", "Cunning.", "Refuse", "Stubborn."),
    ("On the Forest Road", "Landa's wrists in cuffs, his driver dead, your knife in your hand.", "Carve the swastika", "Permanent.", "Let him walk", "Honest."),
    ("Shosanna's Face", "Twenty meters tall on smoke and flame, laughing in a language nobody in the cinema lives to translate.", "Watch", "Final.", "Walk away", "Free."),
], [
    ("end_burn", "Cinema On Fire", "The premier audience does not survive the screening. History tilts. A face in smoke says her own name and means it."),
    ("end_mark", "The Mark", "Landa goes to Washington in a clean uniform with a fresh red swastika on his forehead that no surgeon will ever quite remove."),
    ("end_quiet", "After the War", "You sit in a dark theater with no Nazis in it and you eat strudel without cream and you weep without being seen."),
])

FM_MAD_MAX = linear_story({
    "id": "fm-mad-max-fury-road",
    "title": "Witness Me",
    "sourceTitle": "Mad Max: Fury Road",
    "kind": "movie",
    "synopsis": "A war rig, five wives, and a long road across a desert that goes both ways.",
    "releaseYear": 2015, "addedAt": ADDED, "genre": "Action",
    "tags": ["wasteland", "chase", "survival", "feminist"], "rating": 5, "loved": True,
}, [
    ("Caught at the Rocks", "Hooks pull you down into a place that calls itself the Citadel.", "Fight the chains", "Wild.", "Go limp", "Smart."),
    ("Blood Bag", "Hose in your arm, a mask on your face, a War Boy painted white above you.", "Bide", "Wise.", "Bite", "Wild."),
    ("Furiosa Turns East", "The war rig veers off the spice road into the open dust.", "Trust her plan", "Brave.", "Ride straight", "Stubborn."),
    ("Pursuit", "Joe's whole convoy turns at once, a hundred wheels in a war drum's beat.", "Push the throttle", "Wild.", "Conserve fuel", "Smart."),
    ("The Wives", "Five women in white linen and chain bolt cutters in the bed of the rig.", "Help them", "Honor.", "Use them as leverage", "Cold."),
    ("Nux on the Hood", "A young War Boy with a steering wheel in his fist and chrome in his teeth.", "Pull him in", "Mercy.", "Let him fall", "Hard."),
    ("Canyon Pass", "The Buzzards in spiked cars and a tunnel through living rock.", "Blow the cliffs", "Final.", "Outrun them", "Brave."),
    ("Storm of Sand", "A dust devil the size of a city walks at you in slow motion.", "Drive in", "Wild.", "Go around", "Wise."),
    ("Splendid's Belly", "The pregnant wife stands in the door to shield Furiosa from her husband's bullet.", "Pull her in", "Care.", "Hold the line", "Hard."),
    ("Night in the Mud", "Stuck axle, dead lights, distant engines.", "Push together", "Honor.", "Push alone", "Stubborn."),
    ("Furiosa's Stump", "The mechanical arm is jammed and she will not say it hurts.", "Help her unscrew it", "Care.", "Leave her alone", "Honest."),
    ("Bullet Farmer", "A blind man on a tractor turret shooting by the sound of your tires.", "Decoy", "Cunning.", "Charge", "Brave."),
    ("The Vuvalini", "Old women in motorcycles with bags of seeds and stories.", "Trust them", "Hope.", "Travel alone", "Wary."),
    ("The Green Place", "Crows. Mud. A sky that has not had a green place in it for forty years.", "Go on", "Stubborn.", "Sit down", "Honest."),
    ("Turn Around", "Furiosa decides to drive back through the war party to the Citadel itself.", "Ride", "Final.", "Stay behind", "Honest."),
    ("Salt Flats", "A horizon with no edges, and a hundred engines closing.", "Pour the speed", "Wild.", "Stay tight", "Discipline."),
    ("Nux's Choice", "Witness me, he whispers, and grips a steering wheel one-handed.", "Let him go", "Honor.", "Pull him back", "Mercy."),
    ("Joe at the Window", "His silver mask, your hooked fingers, a moment that does not last.", "Tear it off", "Wild.", "Push him under", "Final."),
    ("Furiosa Bleeding", "A blade through her side and the rig still running on fumes.", "Field dress", "Care.", "Drive faster", "Hard."),
    ("The Gates of the Citadel", "Joe's body on the hood, the dust people staring up at the rig.", "Open the water", "Mercy.", "Drive past", "Cold."),
    ("Lift Up", "Furiosa rises on the platform with the wives, breathing through a tube of your blood.", "Step back into the crowd", "Honest.", "Ride up with her", "Loyal."),
], [
    ("end_water", "Water for All", "The wheels lock, the gates open, and the Citadel learns it was always two days from kindness."),
    ("end_road", "Back to the Road", "You slip down through the crowd before anyone can name you. The road goes both ways and you are not done being driven."),
    ("end_witness", "Witnessed", "Nux's grin in the rearview, half a second before chrome. You will see it for the rest of your long, accidental life."),
])

FM_DIE_HARD = linear_story({
    "id": "fm-die-hard",
    "title": "Nakatomi Christmas",
    "sourceTitle": "Die Hard",
    "kind": "movie",
    "synopsis": "A cop, a tower, a thief in a sweater, and a vault that nobody is supposed to be able to open on Christmas Eve.",
    "releaseYear": 1988, "addedAt": ADDED, "genre": "Action",
    "tags": ["holiday", "siege", "everyman", "vent"], "rating": 5, "loved": True,
}, [
    ("LAX Limo", "Argyle asks about the wife and puts on a Christmas tape.", "Talk", "Honest.", "Sit silent", "Tired."),
    ("Party on the 30th", "Holly. A Rolex. A husband who will not bend.", "Apologize", "Mercy.", "Pick a fight", "Stubborn."),
    ("Shoes Off", "A wise pilot once said, make fists with your toes.", "Do it", "Honest.", "Skip it", "Cool."),
    ("Lobby Goes Loud", "Engines outside, gunfire downstairs, elevator chime.", "Move up", "Smart.", "Move down", "Reckless."),
    ("Vent Shafts", "Crawl on your back over Christmas lights.", "Crawl", "Stubborn.", "Wait", "Cautious."),
    ("Yippee", "A radio in a dead man's belt and a name you should not give.", "Call for help", "Wise.", "Bait Hans", "Cunning."),
    ("Powell at the Curb", "A desk cop with a Twinkie and a steady voice.", "Trust him", "Friend.", "Stay quiet", "Wary."),
    ("Detonators", "C4 above the elevators, fuses in your fist.", "Drop them down the shaft", "Wild.", "Plant them at the door", "Smart."),
    ("Theo at the Keyboard", "Six locks, five dropped, one electromagnetic.", "Sabotage the power grid", "Bold.", "Wait for the FBI", "Smart."),
    ("Karl's Brother", "A boy you killed had a brother who is now hunting you barefoot too.", "Set a trap", "Cunning.", "Run", "Smart."),
    ("Roof Hostages", "Hans drives the partygoers up to the helipad with the C4 still in the elevator shafts.", "Warn them off", "Brave.", "Detonate first", "Final."),
    ("Firehose Dive", "A long hose, a heavier you, a window that won't break easy.", "Jump", "Wild.", "Climb down", "Cautious."),
    ("Ellis", "The cokehead negotiator names you on TV.", "Disavow", "Cold.", "Try to save him", "Honest."),
    ("Hans on the Roof", "Suit, glasses, a polite voice over a stranger's body.", "Play the dumb cop", "Cunning.", "Confront him", "Bold."),
    ("Two Bullets in the Tape", "A roll of holiday tape across your back and a service pistol against your spine.", "Hide them", "Smart.", "Confront", "Reckless."),
    ("FBI Cuts the Power", "Which was the plan all along. The vault clicks open.", "Steal a detonator", "Smart.", "Hide", "Cautious."),
    ("Holly at the Edge", "Hans's hand on her wrist, your gun in your other hand, taped low.", "Tip him off the side", "Hard.", "Talk him down", "Honest."),
    ("Karl Lives", "Outside, dust on his shoulders, an assault rifle aimed at you and the cop.", "Trust Powell", "Friend.", "Charge", "Wild."),
    ("Bonds", "Bearer bonds drifting down on the Christmas lights like ash.", "Watch them fall", "Honest.", "Grab them", "Greedy."),
    ("Ambulance", "Theo at the wheel of a stolen rig, smiling at a window.", "Let Argyle handle it", "Trust.", "Run after him", "Stubborn."),
    ("Holly in the Snow", "Argyle pulls up smiling, and Holly says your name like you forgot it was hers.", "Take her hand", "Heart.", "Apologize first", "Honest."),
], [
    ("end_home", "Christmas Eve, Late", "The limo pulls away. Argyle hums something. Holly leans on you and the radio plays a song you both already know."),
    ("end_back", "Back at the 30th", "You wake at the party in a sweat with shoes on. The Rolex on Hans's wrist on a man falling in slow motion."),
    ("end_powell", "Twinkies on Powell's Desk", "Powell mails you Twinkies every Christmas for ten years. You keep eating them. You keep being okay."),
])

FM_JOHN_WICK = linear_story({
    "id": "fm-john-wick",
    "title": "The Boogeyman",
    "sourceTitle": "John Wick",
    "kind": "movie",
    "synopsis": "A widower, a puppy, a car, and the very specific organization that did not understand who they had just woken up.",
    "releaseYear": 2014, "addedAt": ADDED, "genre": "Action",
    "tags": ["assassins", "revenge", "code", "neon"], "rating": 5, "loved": True,
}, [
    ("Helen", "A package on the doorstep two days after the funeral.", "Open it", "Brave.", "Leave it", "Numb."),
    ("Daisy", "A small dog with a bow and a letter from your dead wife.", "Take her in", "Mercy.", "Send her to a shelter", "Hard."),
    ("Gas Station", "A boy in a tracksuit wants the Mustang.", "Decline", "Calm.", "Threaten", "Hard."),
    ("Home Invasion", "Three men in the house at 3 a.m. with a bat and a tire iron.", "Fight", "Wild.", "Hide and call", "Smart."),
    ("After", "A dog without breath and a car gone and a face in the floorboards you have not worn in years.", "Dig up the cellar", "Final.", "Walk away", "Lost."),
    ("Aurelio", "A chop shop with a code about exactly which dogs you do not steal.", "Ask politely", "Patient.", "Apply pressure", "Hard."),
    ("Viggo's Call", "An old client, an old debt, an old name said into a phone.", "Let him beg", "Cold.", "Hang up", "Cold."),
    ("The Continental", "A hotel with marble floors and a strict rule about no business on the grounds.", "Check in", "Smart.", "Skip it", "Reckless."),
    ("Winston at the Bar", "Bourbon and rules and a man who has seen you do this before.", "Listen", "Wise.", "Decline the drink", "Cold."),
    ("Marcus on the Roof", "An old friend with a rifle and orders from Viggo for double pay.", "Trust him", "Friend.", "Don't trust him", "Wary."),
    ("Red Circle Stairs", "Neon, water, glass, and a hundred men in suits trying very hard to die.", "Move through", "Final.", "Move around", "Smart."),
    ("Ms. Perkins", "A contract violator in a hotel room with a knife and a smile.", "Subdue her", "Discipline.", "Kill her", "Hard."),
    ("The Sommelier", "Tasting notes for guns delivered with a wine pour.", "Choose loud", "Direct.", "Choose dependable", "Wise."),
    ("Iosef in the Garage", "Bratva, hangers-on, a kid who still thinks he is untouchable.", "Make it slow", "Hard.", "Make it quick", "Mercy."),
    ("The Church", "Viggo's slush fund in golden bricks under the altar.", "Burn it", "Final.", "Take it", "Practical."),
    ("Marcus on the Roof, Again", "Two shots that should have killed you both, neither of them his.", "Forgive", "Friend.", "Walk away", "Hard."),
    ("Helen's Necklace", "A small chain found in a drawer, a memory that fills your hands.", "Wear it", "Heart.", "Put it back", "Hard."),
    ("Tarasov Hall", "Viggo, a rocket launcher, an icon of a saint, and a fire spreading.", "End it cleanly", "Discipline.", "Make him beg", "Honest."),
    ("Docks at Dawn", "A long pier, two men past forty, knives that have done this before.", "Use the knee", "Smart.", "Take the cut", "Hard."),
    ("Viggo on the Tarmac", "He goes for the gun on the ground he already dropped.", "Wait", "Final.", "Shoot first", "Quick."),
    ("Animal Hospital", "Locked door, an alarm, a kennel of dogs and one small unclaimed pit bull.", "Take a dog", "Mercy.", "Walk out alone", "Hard."),
], [
    ("end_home", "Walk Home", "Rain on the asphalt. A new dog at your hip. Helen's bench. You sit down and you do not get up for a while."),
    ("end_table", "Back on the Table", "Word travels. The next courier knocks at the kitchen door inside of a week. Daisy growls at the right times."),
    ("end_rule", "No Business on Continental Grounds", "Winston pours one more bourbon. You drink it slow. The Continental has rules; you and it have always agreed about that."),
])

FM_TERMINATOR_2 = linear_story({
    "id": "fm-terminator-2",
    "title": "Hasta La Vista",
    "sourceTitle": "Terminator 2: Judgment Day",
    "kind": "movie",
    "synopsis": "A boy, a mother in a hospital, an old enemy with a new mission, and a polymorphic cop who will not stop.",
    "releaseYear": 1991, "addedAt": ADDED, "genre": "Action",
    "tags": ["time", "robots", "mother", "future"], "rating": 5, "loved": True,
}, [
    ("Sarah in the Cell", "She is on the floor doing pull-ups while a doctor watches her on closed-circuit.", "Keep training", "Hard.", "Bide time", "Smart."),
    ("Arcade", "John, scamming an ATM with a card reader of his own making.", "Take the cash", "Reckless.", "Walk away", "Wise."),
    ("First Encounter", "A truck driver in a leather jacket and a cop with no expression.", "Run with the leather jacket", "Trust.", "Run with the cop", "Doomed."),
    ("Mall Hallway", "Get down. A pump shotgun in slow motion under a fluorescent buzz.", "Duck", "Smart.", "Stand", "Brave."),
    ("Promise", "Swear, says the boy, you will not kill anyone.", "Swear it", "Honor.", "Refuse", "Honest."),
    ("Pescadero", "Sarah is calm in a way that scares the nurses more than the screaming did.", "Break her out", "Loyal.", "Wait", "Cautious."),
    ("Dyson", "An engineer at a kitchen table with a baby asleep upstairs.", "Speak first", "Mercy.", "Aim first", "Hard."),
    ("The Garage", "Plans on the table for a chip that ends the world.", "Persuade him", "Wise.", "Demand he comply", "Hard."),
    ("Cyberdyne", "Lobby, security, helicopter inbound, the whole building one wrong shot from a fire.", "Go up the stairs", "Smart.", "Take the elevator", "Direct."),
    ("Knee Cap Tactics", "Sarah on the radio: no killing.", "Knees only", "Discipline.", "Center mass", "Honest."),
    ("Vault", "The chips spread on a table like a confession.", "Burn it all", "Final.", "Salvage one", "Practical."),
    ("On the Roof", "Police helicopter, then a SWAT van, then a helicopter again.", "Drop down the wall", "Wild.", "Stand still", "Honest."),
    ("Freeway Chase", "A tow truck, a liquid nitrogen tanker, an officer in mirrored shades.", "Ram the tanker", "Bold.", "Outrun", "Cautious."),
    ("Steel Mill", "Catwalks and forging cradles and rivers of orange.", "Set the trap", "Cunning.", "Run", "Cautious."),
    ("Frozen", "The T-1000 in a hundred pieces of fog on the floor.", "Shatter it", "Final.", "Run past", "Smart."),
    ("Reassembly", "It walks back together from a puddle and laughs without lungs.", "Switch weapons", "Smart.", "Stand ground", "Brave."),
    ("Bayonet", "Arm pinned, gear wheel turning, the wrong man down for a beat.", "Pull free", "Brave.", "Wait for him", "Calm."),
    ("Crucible", "Molten steel under your boots and a hand reaching out of the bath.", "Push it in", "Final.", "Step back", "Honest."),
    ("The Last Chip", "The CPU still in his neck. He thinks Sarah cannot do it.", "Lower him", "Final.", "Hesitate", "Heart."),
    ("Sarah's Thumb", "The pulley wheel. A salute the boy will remember for as long as a person can remember.", "Press it", "Honor.", "Pause", "Honest."),
    ("Highway, Night", "Headlights, road stripes, and an unwritten road ahead.", "Drive on", "Hope.", "Pull over", "Honest."),
], [
    ("end_no_fate", "No Fate But What We Make", "Skynet does not boot in 1997. You spend a long quiet decade waiting to see if it boots anyway."),
    ("end_judge", "Judgment, Deferred", "The chips are gone, the engineers persuaded, the date a rumor. A child sleeps. So do you, eventually."),
    ("end_thumbs", "Thumbs Up", "You will hear the cradle in your dreams for the rest of your life. So will the boy. You will be grateful for both."),
])

FM_ALIENS = linear_story({
    "id": "fm-aliens",
    "title": "Game Over Man",
    "sourceTitle": "Aliens",
    "kind": "movie",
    "synopsis": "Marines, a colony gone silent, a little girl in the vents, and a queen who has a very strong opinion about her eggs.",
    "releaseYear": 1986, "addedAt": ADDED, "genre": "Action",
    "tags": ["space", "marines", "queen", "ripley"], "rating": 5, "loved": True,
}, [
    ("Wake Up", "Fifty-seven years of sleep and a hearing about a lifeboat full of nothing.", "Plead for the colony", "Brave.", "Quit and walk", "Honest."),
    ("Express Elevator to Hell", "Drop pod and Hudson loud and Vasquez quiet and a Smartgun checklist on a screen.", "Brief them", "Wise.", "Stay silent", "Tired."),
    ("LV-426 Surface", "Wind. Acid rain. Atmosphere processor humming a wrong chord.", "Sweep the comm tower", "Strategic.", "Sweep the medlab", "Hunch."),
    ("Cocoons", "Colonists in the walls of medlab, two still warm enough to scream.", "Burn them", "Mercy.", "Try to save", "Heart."),
    ("Newt", "A girl in a vent who has not been hugged in weeks.", "Coax her out", "Care.", "Leave her", "Cold."),
    ("Atmosphere Processor", "The reactor under your boots and a sergeant who fires anyway.", "Override the rifle order", "Brave.", "Obey orders", "Loyal."),
    ("Ambush", "Eggs in the dark. Drones from the ceiling. Apone, Dietrich, Frost, Crowe — gone.", "Take the wheel of the APC", "Brave.", "Wait for orders", "Doomed."),
    ("Wreck", "Dropship pilot is foam on a wall. The other ship is gone.", "Improvise the orbit drop", "Brave.", "Fortify and wait", "Smart."),
    ("Burke", "He hopes the Company keeps a specimen alive. He suggests the smuggling routine.", "Confront him", "Honest.", "Watch him quietly", "Cunning."),
    ("Sentry Guns", "Tracers in the corridor and a counter ticking down ammo per second.", "Reposition them", "Smart.", "Stand the line", "Brave."),
    ("Medlab Facehuggers", "Two in a cage that is unlocked.", "Lock it again", "Smart.", "Burn them", "Final."),
    ("Hicks at the Door", "He hands you a tracker bracelet for Newt and a careful first name.", "Wear it", "Care.", "Refuse", "Hard."),
    ("Vents Above", "Sound of a wet thing moving past a grille.", "Drop a flare", "Cunning.", "Stay still", "Patient."),
    ("Newt in the Wall", "A vent slips and pulls her down a chute toward a darkness with eyes in it.", "Crawl after her", "Loyal.", "Cut through the floor", "Brave."),
    ("Power to the Reactor", "It is going critical and the windows are starting to flex.", "Set the timer", "Final.", "Cut the cooling now", "Reckless."),
    ("Burke at the Lock", "He has locked you out and run for the dropship.", "Track him with the bracelet", "Smart.", "Wait", "Calm."),
    ("Hive", "Eggs in long rows, and at the center, a swaying mother with new breath.", "Burn the eggs", "Final.", "Sneak past", "Cautious."),
    ("Queen's Bargain", "She lifts her ovipositor and gestures: leave, and we leave.", "Burn anyway", "Hard.", "Walk slowly back", "Wise."),
    ("Dropship Pad", "Bishop at the controls, half a man, all the way arrived.", "Hand him Newt first", "Care.", "Cover the rear", "Brave."),
    ("Cargo Bay", "Queen on the underside of the ship, eggs in her teeth.", "Power loader", "Bold.", "Vent the bay", "Final."),
    ("Get Away From Her", "Loader arms, claws, the cold of space waiting just past the door.", "Open the airlock", "Final.", "Spin her into the lift", "Cunning."),
], [
    ("end_sleep", "Sleep Easy", "Bishop's torso in a cot, Newt's small hand in yours, a fifty-year ride home with better dreams this time."),
    ("end_hold", "Hold the Line", "You come back to the surface anyway, with five hundred Colonial Marines and a plan that the Queen has not yet predicted."),
    ("end_quiet", "Newt Asleep", "She asks if she can dream now. You say yes. She does. So do you. Both of you for the first time in weeks."),
])

ACTION_SPECS = [FM_LOTR_RETURN, FM_LOTR_TWO_TOWERS, FM_EMPIRE_STRIKES_BACK, FM_GLADIATOR,
                FM_INGLOURIOUS, FM_MAD_MAX, FM_DIE_HARD, FM_JOHN_WICK, FM_TERMINATOR_2, FM_ALIENS]
