# Top 10 Drama picks from IMDb Top 250 (skipping titles already in fm- catalog).
from stories_data import linear_story

ADDED = "2026-06-03T00:00:00Z"

FM_GODFATHER_II = linear_story({
    "id": "fm-godfather-ii",
    "title": "Michael in Tahoe",
    "sourceTitle": "The Godfather Part II",
    "kind": "movie",
    "synopsis": "A young Vito in New York, a cold Michael in Nevada, and a family that does not survive its own success.",
    "releaseYear": 1974, "addedAt": ADDED, "genre": "Drama",
    "tags": ["family", "crime", "parallel", "betrayal"], "rating": 5, "loved": True,
}, [
    ("Communion Party", "A senator in your study with a hand on his price.", "Refuse him", "Stern.", "Buy him", "Calm."),
    ("Shot Through the Bedroom Window", "Glass on the rug and Kay alive by an inch.", "Hunt the shooter", "Cold.", "Send the family away", "Care."),
    ("Pentangelo", "Frankie at the Vegas hotel asks for a meeting and a name.", "Promise help", "Cunning.", "Promise nothing", "Honest."),
    ("Hyman Roth in Miami", "Cake on a card table, a number written on a candle.", "Smile and listen", "Patient.", "Object", "Pride."),
    ("Havana New Year", "Fireworks, a kiss on a brother's mouth, the click of a regime.", "Move the deal", "Cold.", "Walk away", "Wise."),
    ("Fredo, on the Balcony", "I knew it was you, Fredo. I knew it was you.", "Embrace him", "Cold.", "Spare him today", "Calm."),
    ("Young Vito's Crate", "An olive press in a Little Italy basement and a Black Hand who wants a tax.", "Refuse him", "Brave.", "Pay him", "Patient."),
    ("Fanucci", "Festa night, a white suit, a stairwell that knows you are coming.", "Three shots", "Final.", "Two and a knife", "Quiet."),
    ("Senate Subcommittee", "Cameras, a microphone, a lawyer at your shoulder.", "Plead the Fifth", "Smart.", "Speak", "Pride."),
    ("Pentangelo's Brother", "A man from Sicily in the gallery in a black hat.", "Let him be seen", "Cold.", "Hide him", "Mercy."),
    ("Kay's Confession", "An abortion, not a miscarriage. Said to your face in a quiet kitchen.", "Strike her", "Hard.", "Walk out", "Cold."),
    ("Tom Hagen, On the Lake", "He brings the news that Pentangelo will fall on his sword.", "Allow it", "Cold.", "Refuse", "Honest."),
    ("Don Ciccio in Sicily", "A young Vito with an orange and a switchblade and a promise to a mother.", "Speak the names", "Final.", "Strike quiet", "Cold."),
    ("Mother's Funeral", "The casket carried by hands that have killed for the family.", "Spare Fredo here", "Mercy.", "Wait", "Cold."),
    ("Connie Returns Home", "A sister broken and useful and sober for the first time in years.", "Take her in", "Family.", "Refuse", "Hard."),
    ("Roth at the Airport", "Cancer in him, marshals on him, a single shot needed before he steps onto Israeli soil.", "Order it", "Final.", "Withdraw", "Wise."),
    ("Fredo Praying", "Hail Mary by a boat on the lake at dusk.", "Order Neri now", "Final.", "Wait", "Mercy."),
    ("Kay at the Door", "She has come back for the children and not for you.", "Slam it", "Final.", "Let her see them", "Mercy."),
    ("A Flashback to a Birthday", "Sonny, Tessio, Fredo, the table set, an empty chair for a father late from work.", "Smile", "Honest.", "Get up alone", "Cold."),
    ("Lake at Dawn", "A small craft drifting and a brother gone under and a silence that is your inheritance.", "Sit", "Final.", "Walk back", "Honest."),
    ("Empty Study", "A leather chair, an open door, your father's photograph small on a side table.", "Sit in the chair", "Cold.", "Stand", "Honest."),
], [
    ("end_throne", "King of Nothing", "You own everything you can see from the lake. There is no one left to share it with. You sit anyway, like a king."),
    ("end_walk", "Walking the Vineyard", "You go to Sicily under the orange trees and you read the same psalm every morning. You are still cold. The trees do not mind."),
    ("end_kay", "The Door Stays Open", "Kay's eyes through the closing door for forty years. You will see them when you die. You already see them now."),
])

FM_12_ANGRY_MEN = linear_story({
    "id": "fm-12-angry-men",
    "title": "Twelve Angry Men",
    "sourceTitle": "12 Angry Men",
    "kind": "movie",
    "synopsis": "A jury room, a stalled fan, a knife on a table, and one juror asking whether reasonable doubt has been considered.",
    "releaseYear": 1957, "addedAt": ADDED, "genre": "Drama",
    "tags": ["jury", "doubt", "single-room", "ethics"], "rating": 5, "loved": True,
}, [
    ("First Vote", "Eleven hands up for guilty, fast, in a hot room.", "Raise your hand", "Honest.", "Hold it down", "Brave."),
    ("Why Not", "Foreman asks for a reason and the room stares.", "Speak", "Honest.", "Pass", "Cautious."),
    ("Switchblade", "Juror Eight pulls an identical knife from his pocket.", "Lay it on the table", "Bold.", "Pocket it again", "Quiet."),
    ("Old Man's Limp", "He testified he ran to his door in fifteen seconds.", "Time it on the floor", "Practical.", "Trust him", "Loyal."),
    ("El", "Train under the window during the scream.", "Time the rumble", "Wise.", "Move past", "Cautious."),
    ("Glasses", "The marks on a woman's nose at the trial.", "Speak the detail", "Sharp.", "Hold it", "Patient."),
    ("Switch", "A second vote, secret ballot. Nine to three.", "Take the credit", "Pride.", "Listen for who switched", "Wise."),
    ("Garage Owner", "He says he never even gets emotional about anything.", "Press him", "Hard.", "Soften him", "Wise."),
    ("Architect's Diagram", "A floorplan in chalk on a table cloth.", "Walk it", "Patient.", "Argue it", "Brave."),
    ("Stockbroker", "Cold facts, cold tone, a deep certainty.", "Engage", "Discipline.", "Wait", "Patient."),
    ("Salesman", "He has tickets to a game and he wants the room to vote.", "Shame him", "Hard.", "Persuade him", "Wise."),
    ("Prejudice", "A juror says these people, they're all like that.", "Stand", "Brave.", "Sit silent", "Cold."),
    ("Old Juror Speaks", "The eldest finds words for what the youngest just felt.", "Listen", "Wise.", "Interrupt", "Pride."),
    ("Tired Lawyer", "The defense was sleepy and you are not.", "Note it for the room", "Sharp.", "Hold it", "Cautious."),
    ("Memory Test", "Ask Juror Four what movie he saw last week.", "Press for detail", "Cunning.", "Move on", "Polite."),
    ("Hot Day Cooling", "Rain on the windows finally and the fan starts at the right second.", "Open the window", "Calm.", "Stay seated", "Patient."),
    ("Knife in the Door", "Eight stabs the table to argue an unlikely angle.", "Approve the demonstration", "Honest.", "Object", "Cold."),
    ("Three to Acquit", "The room has flipped under you and you are still standing.", "Concede gracefully", "Honest.", "Hold out", "Pride."),
    ("One Holdout", "Juror Three with a wallet photo and a son he hasn't spoken to.", "Wait", "Patient.", "Confront", "Hard."),
    ("Photograph Torn", "A son's face on the floor and a father's face in his hands.", "Help him up", "Mercy.", "Wait", "Honest."),
    ("Not Guilty", "Twelve hands raised slowly, no triumph in any of them.", "File out quietly", "Honest.", "Shake hands", "Honest."),
], [
    ("end_rain", "Rain on the Steps", "You walk down the courthouse steps with a stranger whose first name you finally learn. You do not exchange numbers. You do not need to."),
    ("end_doubt", "Reasonable", "The boy walks. He is innocent or guilty and the room never found out. You learn to live with that distinction, which is the entire point."),
    ("end_three", "The Photograph", "Juror Three calls his son that night from a payphone, and the line is busy. He calls again at six in the morning. He calls every day until it is not."),
])

FM_FIGHT_CLUB = linear_story({
    "id": "fm-fight-club",
    "title": "Project Mayhem",
    "sourceTitle": "Fight Club",
    "kind": "movie",
    "synopsis": "Insomnia, soap, a basement, and a man in the mirror who has finally caught up to you.",
    "releaseYear": 1999, "addedAt": ADDED, "genre": "Drama",
    "tags": ["identity", "consumer", "split", "subversion"], "rating": 5, "loved": True,
}, [
    ("Support Group", "Cancer rooms full of hugs and a real grief that is not yours.", "Cry honestly", "Honest.", "Fake it", "Cold."),
    ("Marla", "She is a tourist too, and she sees you the way you see her.", "Confront her", "Bold.", "Avoid her", "Cowardly."),
    ("Plane Aisle Conversation", "A man with a briefcase and a perfect smile and a card you keep.", "Take the card", "Curious.", "Decline", "Wise."),
    ("Condo on Fire", "Your IKEA life sublimated into smoke.", "Call Tyler", "Lost.", "Call Marla", "Honest."),
    ("First Hit", "Outside a bar, on a curb, his request.", "Hit him", "Brave.", "Refuse", "Honest."),
    ("Basement Rules", "Eight of them, the first two the same.", "Recite them", "Loyal.", "Walk away", "Wise."),
    ("Marla in the Bathtub", "Lye and water and a moan that is not pain.", "Listen at the door", "Curious.", "Walk past", "Polite."),
    ("Soap", "Liposuction fat boiled into bars sold back to the people it came from.", "Sell it", "Strategic.", "Refuse", "Honest."),
    ("Lou's Tavern", "Lou comes downstairs with a bat and you smile through teeth.", "Bleed on him", "Wild.", "Hold up your hands", "Smart."),
    ("Homework", "A handle of vinegar, a credit company, a parking lot in the rain.", "Carry it out", "Loyal.", "Refuse the task", "Honest."),
    ("Bob", "Big arms, soft chest, a hug like a wall.", "Hug back", "Honest.", "Push him off", "Cold."),
    ("Cornelius", "The name you give at the support groups, a second skin.", "Keep it", "Cunning.", "Drop it", "Honest."),
    ("Space Monkeys", "Men in black shirts at attention on a porch.", "Lead them", "Pride.", "Stop them", "Honest."),
    ("The Bomb in the Building", "A van under a tower, a fuse in a basement, a timer running.", "Confront Tyler", "Brave.", "Help set it", "Lost."),
    ("Tyler Tied to a Chair", "Except Tyler is not in the chair.", "Look in the mirror", "Honest.", "Run", "Frightened."),
    ("Marla, Endangered", "He has set her up too, somehow.", "Warn her", "Mercy.", "Go on", "Cold."),
    ("Garage Brawl, Alone", "Bruises blooming on your own face from a fight you are losing to yourself.", "Take the hits", "Honest.", "Surrender", "Wise."),
    ("Parking Garage", "Tyler at the wheel, you in the passenger seat, hands off the wheel.", "Grab the wheel", "Brave.", "Let go", "Lost."),
    ("Skyscraper", "A view of the city through your own eye and his hand on your gun in your mouth.", "Pull the trigger", "Final.", "Refuse", "Brave."),
    ("Detonators on Schedule", "Eleven buildings around you starting to lean.", "Cover Marla's eyes", "Mercy.", "Make her look", "Honest."),
    ("Hand in Hand", "You meet me at a very strange time in my life.", "Hold on", "Honest.", "Let go", "Lost."),
], [
    ("end_collapse", "The Buildings Fall", "You stand at a window with Marla's small fingers in yours and watch your debt erase itself in dust. Tomorrow has not been invented yet."),
    ("end_quiet", "First Rule, Reversed", "You go to a meeting and talk, finally, about the second man in your mirror. The room listens. The room has heard this before."),
    ("end_marla", "Pillow Talk", "She takes you home. She asks your real name. You give it. It is the first thing you have said out loud in months that you actually meant."),
])

FM_ONE_FLEW_OVER = linear_story({
    "id": "fm-one-flew-over",
    "title": "McMurphy on the Ward",
    "sourceTitle": "One Flew Over the Cuckoo's Nest",
    "kind": "movie",
    "synopsis": "A work-farm transfer, a card table, a fishing trip, and a quiet Indian by a window who has been listening the whole time.",
    "releaseYear": 1975, "addedAt": ADDED, "genre": "Drama",
    "tags": ["asylum", "rebellion", "freedom", "ratched"], "rating": 5, "loved": True,
}, [
    ("Intake", "A nurse in starched white at a glass window with a clipboard.", "Smile big", "Cunning.", "Stay quiet", "Wary."),
    ("Med Cart", "A small paper cup with three pills and a name on the side.", "Refuse", "Brave.", "Swallow", "Wise."),
    ("Cards", "Cheswick antes a cigarette and Billy stutters a bet.", "Teach them", "Friend.", "Hustle them", "Hard."),
    ("Chief", "He is six and a half feet tall and pretends he can't hear anything.", "Speak to him", "Curious.", "Leave him be", "Polite."),
    ("World Series Vote", "Hands up against a fixed schedule and a clock at 4.", "Mime the game", "Wild.", "Sit silent", "Cold."),
    ("Group", "Ratched asks Billy about his mother in front of everyone.", "Interrupt", "Brave.", "Wait", "Cautious."),
    ("Basketball with Chief", "He blocks a shot and the smile is brief and bright.", "Pass to him", "Friend.", "Take the shot", "Pride."),
    ("Bus Hijack", "A field trip, then a sudden left turn and a stolen vessel.", "Take the wheel", "Wild.", "Hold the door", "Loyal."),
    ("Fishing Boat", "Twelve patients in life jackets, line out, sun on the water.", "Let Cheswick captain", "Friend.", "Helm yourself", "Pride."),
    ("Cheswick's Cigarettes", "Confiscated. A small loss that is not small.", "Riot for them", "Brave.", "Speak slowly", "Wise."),
    ("Electroshock", "A bite block and a hand on your wrist and the smell of ozone.", "Brace", "Brave.", "Refuse", "Honest."),
    ("Chief Speaks", "A whisper at night that he was not deaf, not really.", "Listen", "Friend.", "Doubt", "Wary."),
    ("Plan", "A window, a key, a Christmas Eve nurse asleep at her desk.", "Stay", "Loyal.", "Run alone", "Cold."),
    ("Candy", "Two women in a station wagon at midnight, a bottle of liquor.", "Let them in", "Reckless.", "Wave them off", "Smart."),
    ("Billy's Night", "A bedroom door, a girl with kindness, a stutter that disappears for a few hours.", "Stand guard", "Friend.", "Wake the ward", "Reckless."),
    ("Morning", "Ratched in the doorway with a face like ice.", "Confront her", "Brave.", "Hide Billy", "Care."),
    ("Billy's Mother", "She will be told, she says. The word breaks him on the floor.", "Step between", "Brave.", "Plead", "Honest."),
    ("Glass Broken", "A doctor's office, a body on the desk, an answer not heard until too late.", "Lift Billy", "Care.", "Run", "Cold."),
    ("Hands on Her Throat", "A neck under your thumbs, a window over a quiet lawn.", "Squeeze", "Wild.", "Release", "Honest."),
    ("After", "A bed, a strap, a smile that doesn't reach the eyes.", "Wait for Chief", "Trust.", "Wait alone", "Honest."),
    ("Pillow", "Chief lifts the pillow with both hands.", "Look him in the eye", "Honor.", "Close your eyes", "Mercy."),
], [
    ("end_window", "Through the Window", "Chief lifts the sink and walks out into a morning that smells of cut grass. Somewhere, you are running with him. Somewhere else, you are at rest."),
    ("end_card", "The Card Table", "The men learn poker. They learn it well. They lose a thousand games to each other and not one to the house, ever again."),
    ("end_chief", "Chief's Voice", "He goes back to Canada through fields nobody owns. He talks now. Mostly to a stranger he keeps in his head, in a leather jacket, smiling like a mouth full of cards."),
])

FM_WONDERFUL_LIFE = linear_story({
    "id": "fm-its-wonderful-life",
    "title": "Bedford Falls",
    "sourceTitle": "It's a Wonderful Life",
    "kind": "movie",
    "synopsis": "A small-town banker on a bridge, an angel earning his wings, and a Christmas Eve that becomes a ledger of every kindness you forgot doing.",
    "releaseYear": 1946, "addedAt": ADDED, "genre": "Drama",
    "tags": ["holiday", "angel", "small-town", "second-chance"], "rating": 5, "loved": True,
}, [
    ("Drug Store, 1919", "Mr. Gower has a telegram in one hand and gin on his breath.", "Hold the capsules", "Brave.", "Deliver them", "Loyal."),
    ("Charleston at the Dance Floor", "A waxed gym floor that opens onto a pool.", "Lean back", "Reckless.", "Catch the falling girl", "Heart."),
    ("Moon for Mary", "She would, if you would, lasso it.", "Lasso", "Heart.", "Laugh it off", "Honest."),
    ("Pop's Stroke", "A father on the floor of an office that is not yours, yet.", "Take the desk", "Duty.", "Refuse", "Honest."),
    ("Harry's Wedding", "Your brother home from college with a bride and a new job.", "Hold the news", "Care.", "Tell him", "Honest."),
    ("Building and Loan Run", "A line at the counter and four thousand dollars total in the drawer.", "Speak to them", "Hope.", "Close the doors", "Cold."),
    ("Honeymoon Money", "Two thousand dollars for the company instead of a train.", "Spend it", "Care.", "Keep it", "Pride."),
    ("Bailey Park", "Plain houses on plain streets, owned by people who lived in slums.", "Tour them through", "Pride.", "Stay at the desk", "Tired."),
    ("Potter's Office", "Twenty thousand a year and a cigar.", "Refuse the cigar", "Honest.", "Take the offer", "Tempted."),
    ("Pharmacy Return", "Old Mr. Gower in a Christmas line, embracing you in front of strangers.", "Embrace him", "Heart.", "Brush past", "Cold."),
    ("Zuzu's Petals", "She gives you her flower; you tuck the petals into your watch pocket.", "Promise to fix it", "Heart.", "Be honest", "Tired."),
    ("Uncle Billy's Bundle", "The eight thousand dollars in a newspaper a banker leaves on a counter.", "Search the streets", "Frantic.", "Calm yourself", "Wise."),
    ("Potter Across the Desk", "He smells the panic and offers a noose.", "Beg", "Honest.", "Walk out", "Pride."),
    ("Bedroom, Late", "Snapping at the children for being children.", "Apologize", "Honest.", "Storm out", "Cold."),
    ("Bridge", "Snow on the rail, a long dark river below.", "Climb up", "Lost.", "Step back", "Hope."),
    ("Clarence", "An old man in dripping clothes, a book under his arm.", "Help him", "Honest.", "Wish yourself away", "Lost."),
    ("Pottersville", "Neon and dance halls and a wife who does not know you.", "Run", "Frightened.", "Look closer", "Honest."),
    ("Mr. Gower in the Gutter", "Twenty years for the capsules you did not hold back.", "Lift him up", "Mercy.", "Walk past", "Cold."),
    ("Harry's Grave", "Nine men on a transport who died because nobody was there to save Harry from the ice.", "Pray", "Honest.", "Run home", "Brave."),
    ("Bridge Again", "Snow back where it belongs, your prayer answered.", "Want to live", "Honest.", "Hesitate", "Tired."),
    ("Living Room", "A basket of cash and a town in your living room and a bell on the tree.", "Hold Mary", "Heart.", "Stand still", "Honest."),
], [
    ("end_friends", "No Man Is a Failure", "The whole town files past with what they can spare. Harry toasts you. A bell rings. Zuzu says it means an angel got his wings."),
    ("end_quiet", "Quiet Christmas", "You sit on the floor with the children and you do not look at the basket of money for a long time. You just look at them."),
    ("end_potter", "Potter, Alone", "Across town, an old man in a wheelchair sits with a stolen bundle on his desk and does not, for the first time, count it."),
])

FM_PRESTIGE = linear_story({
    "id": "fm-prestige",
    "title": "The Pledge",
    "sourceTitle": "The Prestige",
    "kind": "movie",
    "synopsis": "Two magicians, a transported man, a tank of water, and a notebook that may be telling the truth or the better lie.",
    "releaseYear": 2006, "addedAt": ADDED, "genre": "Drama",
    "tags": ["magic", "rivalry", "secrets", "twist"], "rating": 5, "loved": True,
}, [
    ("Sarah's Tank", "A trick gone wrong on a stage in front of strangers.", "Tie a slipknot", "Smart.", "Use a true knot", "Reckless."),
    ("Funeral", "A coffin, a brother, a hard look across an open grave.", "Speak", "Honest.", "Stay quiet", "Cold."),
    ("Borden's Code Book", "A notebook in cipher with a single mocking word.", "Steal it", "Wild.", "Wait", "Patient."),
    ("Tesla's Telegram", "Colorado Springs. A current. A demonstration in a barn.", "Travel", "Brave.", "Refuse", "Cautious."),
    ("Olivia", "A new assistant who is too clever and too kind by half.", "Trust her", "Heart.", "Use her", "Cold."),
    ("Catch and Release", "A bird in a cage, a smashing trick, a feather on a sleeve.", "Show it whole", "Honest.", "Burn the cage", "Hard."),
    ("Bullet Catch", "A volunteer with a smug grin loads a real round.", "Step closer", "Brave.", "Refuse the trick", "Wise."),
    ("Two Fingers Gone", "A cost to a trick written into your own hand.", "Hide it", "Pride.", "Show the audience", "Honest."),
    ("Tesla's Machine", "A copper coil and a hat that arrives twice.", "Take it home", "Brave.", "Leave it", "Wise."),
    ("Drowned in a Tank", "A trick where the magician disappears below stage every night.", "Investigate", "Curious.", "Stop performing", "Wise."),
    ("Sally", "A small daughter who must be home before bedtime.", "Make time", "Heart.", "Skip the lullaby", "Cold."),
    ("Fallon", "A bearded engineer who never leaves the workshop.", "Question him", "Wise.", "Hire him", "Practical."),
    ("Show Beneath the Stage", "Doubles in mirrors and a man dripping in a hidden bath.", "Climb down", "Brave.", "Run", "Smart."),
    ("Trick Gone Public", "A poster announcing one hundred nights of the new transported man.", "Sabotage the show", "Wild.", "Steal the gimmick", "Cunning."),
    ("Olivia's Reveal", "She has been Borden's all along and she is sorry.", "Forgive", "Heart.", "Hate", "Cold."),
    ("The Cat in the Box", "A small dead twin in the workshop drawer.", "Bury it", "Honest.", "Stage it", "Cold."),
    ("Trial", "A judge, a courtroom, a verdict already written.", "Confess", "Honest.", "Lie", "Cunning."),
    ("Lord Caldlow", "A baronet with a daughter and a checkbook and a polite cruelty.", "Refuse him", "Honest.", "Accept", "Cold."),
    ("Tanks Below Stage", "A row of drowned magicians like a museum.", "Smash the tanks", "Final.", "Walk past", "Cold."),
    ("Gallows", "A trapdoor, a hood, a small word said into the canvas.", "Forgive", "Mercy.", "Curse", "Cold."),
    ("Workshop in Flames", "A bullet, a brother, a daughter handed back across a counter.", "Take her home", "Heart.", "Stay to burn", "Cold."),
], [
    ("end_prestige", "The Prestige", "You sit at last in front of a small girl who calls you Daddy and does not know which of you that is. You hold her hand. You agree, both of you, that it is."),
    ("end_lie", "The Beautiful Lie", "Audiences fill the theater for a year. They want to be fooled. You give them their money's worth, again and again, until the lie wears thin and you sleep."),
    ("end_truth", "The Cost", "You publish the notebook. Magic, in your city, dies a little. So do you. So does Angier, in his way. The next century will reinvent both."),
])

FM_DEPARTED = linear_story({
    "id": "fm-departed",
    "title": "Rats in the Wall",
    "sourceTitle": "The Departed",
    "kind": "movie",
    "synopsis": "A South Boston cop undercover in the Mob, a Mob mole undercover in the cops, and a question of who calls whose phone first.",
    "releaseYear": 2006, "addedAt": ADDED, "genre": "Drama",
    "tags": ["undercover", "boston", "scorsese", "double"], "rating": 5, "loved": True,
}, [
    ("Costello at the Counter", "He sees you as a boy in a deli and he sees what he can use.", "Take the envelope", "Tempted.", "Refuse", "Honest."),
    ("State Police Academy", "A class of cadets, a sergeant with a file with your name on it.", "Volunteer to go deep", "Brave.", "Take the badge", "Safe."),
    ("Cousin Sean", "Old neighborhood, old contempt, an opening across the bar.", "Talk to him", "Smart.", "Walk past", "Cold."),
    ("Madolyn", "A psychiatrist with a sharp pen and a softer voice.", "Open up", "Heart.", "Lie", "Cold."),
    ("First Fight", "A bar, a smashed glass, an audition.", "Hit first", "Brave.", "Take the hit", "Smart."),
    ("Costello's Inner Ring", "French, Fitzy, a Chinese deal at a Quincy warehouse.", "Watch", "Patient.", "Act", "Reckless."),
    ("Microprocessors", "Servers in crates trundled across a wet warehouse floor.", "Tip the cops", "Brave.", "Stay silent", "Smart."),
    ("Tap", "A wire under a folder in the captain's drawer.", "Plant it", "Cold.", "Pull back", "Honest."),
    ("Queenan on the Roof", "Captain Queenan in a coat, your name in your mouth.", "Meet him", "Brave.", "Cancel", "Cautious."),
    ("Stairs", "Falling glass, a body on the pavement, a phone in pieces on a roof.", "Run", "Brave.", "Confront", "Reckless."),
    ("Madolyn's Apartment", "Toothbrush left on a counter that is not yours.", "Stay", "Heart.", "Leave", "Honest."),
    ("Rat on the Tape", "Costello has been an FBI asset for years.", "Tell Dignam", "Honest.", "Use it", "Cunning."),
    ("Envelope to the Captain", "Manila, blank face, a name in pencil.", "Hand it over", "Brave.", "Wait", "Patient."),
    ("Funeral for Queenan", "A folded flag, a son who looks like the father.", "Speak to the widow", "Honest.", "Walk past", "Cold."),
    ("Citizens' Affairs", "An audit that wants to know exactly what your unit has been doing.", "Open the books", "Honest.", "Stall", "Cunning."),
    ("Sullivan in the Locker Room", "A friendly word, a clap on the shoulder, a phone that has been calling Costello.", "Watch him", "Patient.", "Confront him", "Brave."),
    ("Costello Cornered", "An alley by the Charles, a phone clutched to his ear, the cops at both ends.", "Pull the trigger", "Final.", "Arrest him", "Honest."),
    ("Envelope Delivered", "Madolyn opens it on a kitchen table you used to share.", "Don't be there", "Mercy.", "Wait outside", "Honest."),
    ("Elevator", "Doors open on a familiar face you used to drink with.", "Draw", "Quick.", "Speak", "Honest."),
    ("Roof", "A second cop with a quieter gun than yours.", "Trust him", "Honest.", "Don't", "Wary."),
    ("Apartment Door", "A clean uniform, a key in a lock, a long ride down to the floor.", "Look him in the eye", "Final.", "Close your eyes", "Tired."),
], [
    ("end_rat", "The Rat in the Window", "A rodent runs across the railing in the dawn. The city is gray. Justice has not arrived; arithmetic has."),
    ("end_card", "Citizens' Award", "A medal in a frame on a wall in a room nobody goes into. A widow throws the envelope away unopened, then digs it back out."),
    ("end_quiet", "Madolyn, Alone", "She raises the boy in a town her family does not know. A photograph on the dresser. She does not say which father he looks like."),
])

FM_GREEN_MILE = linear_story({
    "id": "fm-green-mile",
    "title": "John Coffey, Like the Drink",
    "sourceTitle": "The Green Mile",
    "kind": "movie",
    "synopsis": "A death row in 1935, a giant inmate who heals what he touches, and a guard who has to decide what mercy means in a green corridor.",
    "releaseYear": 1999, "addedAt": ADDED, "genre": "Drama",
    "tags": ["prison", "miracle", "execution", "kindness"], "rating": 5, "loved": True,
}, [
    ("Mr. Jingles", "A mouse on the green linoleum that everyone pretends not to see.", "Leave a crumb", "Mercy.", "Set the trap", "Cold."),
    ("New Inmate", "Six feet eight, hands the size of dinner plates, weeping.", "Lead him gently", "Care.", "Cuff him hard", "Hard."),
    ("Percy", "A nephew of a governor with a baton and a small cruelty.", "Stand up to him", "Brave.", "Manage him", "Wise."),
    ("Bladder, Burning", "A urinary infection that will kill you slowly.", "See a doctor", "Wise.", "Push through", "Stubborn."),
    ("Coffey's Hands", "He asks for your face, palms up.", "Let him", "Brave.", "Refuse", "Cautious."),
    ("Healed", "A pain that was a wall is suddenly a door.", "Tell the warden", "Honest.", "Tell no one", "Wise."),
    ("Wild Bill", "A new inmate, a yellow grin, a habit of spitting.", "Keep him chained", "Hard.", "Try kindness", "Hope."),
    ("Del's Mouse", "A miracle in cupped hands, a tail in fingers like a thread.", "Watch", "Honest.", "Smile", "Heart."),
    ("Mr. Jingles Performs", "A spool, a song, a trick learned in a quiet cell.", "Applaud", "Heart.", "Stay neutral", "Honest."),
    ("Sponge Dry", "Percy forgets the wet sponge for the chair on purpose.", "Hit Percy", "Brave.", "Hold the line", "Discipline."),
    ("Del at the Chair", "The smell, the screaming, a thing nobody who was there ever forgets.", "Look", "Honor.", "Look away", "Mercy."),
    ("Visit to the Warden's Wife", "Melinda is dying of a brain tumor and a smile that is no longer hers.", "Take Coffey", "Brave.", "Stay", "Wise."),
    ("Touch", "He sucks the sickness into his mouth like flies.", "Watch", "Honest.", "Pray", "Heart."),
    ("Sick Black Cloud", "He spits the bugs into the air over a kitchen sink.", "Lock the doors", "Wise.", "Open the window", "Honest."),
    ("Percy", "A man cured of nothing has Coffey's mouth on his and inherits the curse.", "Let it happen", "Hard.", "Pull him off", "Mercy."),
    ("Wild Bill, Crowed", "He grins through bars and brags about two little girls in a barn.", "Restrain Percy", "Discipline.", "Step back", "Honest."),
    ("Two Shots", "Six rounds emptied into a cell by a man who has been spelled.", "Take the gun", "Calm.", "Wait", "Honest."),
    ("Coffey's Truth", "He says he saw what Wild Bill did and he is tired, boss.", "Believe him", "Honest.", "Doubt", "Cautious."),
    ("Last Meal", "Cornbread, okra, sweet potato pie, the kindness of a cook.", "Sit with him", "Honor.", "Stand", "Cold."),
    ("Hood", "He asks if he can go without it. The room is full of strangers.", "Refuse, gently", "Discipline.", "Allow it", "Mercy."),
    ("Switch", "Your hand on a lever, his eyes on yours, his last words a small request.", "Throw it", "Final.", "Stop the execution", "Brave."),
], [
    ("end_long", "The Long Goodbye", "Mr. Jingles is alive in a small wooden cage forty years later, and so are you, both of you tired of staying."),
    ("end_quiet", "A Quiet Pension", "You leave the prison. You marry a kind woman. You wake up at night with green linoleum in your dreams. It does not let you go."),
    ("end_pray", "Coffey's Prayer", "On a hill behind the prison you bury a man with hands like dinner plates. You pray for a mercy you do not believe in, and it comes anyway."),
])

FM_AMERICAN_HISTORY_X = linear_story({
    "id": "fm-american-history-x",
    "title": "Curb",
    "sourceTitle": "American History X",
    "kind": "movie",
    "synopsis": "A skinhead, a brother who idolizes him, three years inside, and a return to a city that hasn't waited.",
    "releaseYear": 1998, "addedAt": ADDED, "genre": "Drama",
    "tags": ["redemption", "racism", "brothers", "prison"], "rating": 5, "loved": True,
}, [
    ("Murray's Class", "A teacher who asks for a paper on a book you would not have chosen.", "Write the paper", "Honest.", "Refuse", "Pride."),
    ("Dad's Dinner Table", "A monologue in the kitchen that becomes an inheritance.", "Listen quietly", "Doubt.", "Agree loudly", "Lost."),
    ("Fire House", "A father in a uniform shot at a call in a neighborhood he did not respect.", "Grieve", "Honest.", "Blame", "Lost."),
    ("Truck on the Curb", "Three men, a window broken, a boot at the curb.", "Walk away", "Brave.", "Press the foot down", "Final."),
    ("Sentencing", "Three years, a wife crying, a brother in the back row.", "Look at him", "Honor.", "Look away", "Cold."),
    ("Laundry", "Lamont with a half-grin and a sock joke.", "Laugh", "Honest.", "Stay cold", "Pride."),
    ("Shower", "Two men in the steam with a smile that is not a smile.", "Fight", "Brave.", "Run", "Smart."),
    ("Yard", "An Aryan brotherhood that wants you to nod.", "Sit alone", "Brave.", "Sit with them", "Tempted."),
    ("Lamont in the Hallway", "He covered for you in the laundry without a reason.", "Thank him", "Honest.", "Pretend it didn't happen", "Cold."),
    ("Letters", "Murray writes weekly. The handwriting is patient.", "Write back", "Honest.", "Burn them", "Pride."),
    ("Visit from Doris", "Mother in a coat that doesn't fit, sister in heels too high.", "Apologize", "Honest.", "Bristle", "Cold."),
    ("Library Books", "Frederick Douglass left on a cot in a stack.", "Read", "Curious.", "Push aside", "Pride."),
    ("Release", "A bus from upstate, a bag with a notebook, a brother on a curb.", "Embrace him", "Heart.", "Lecture him", "Cold."),
    ("Cameron in the Living Room", "An old mentor with the same speech and a softer chair.", "Walk out", "Brave.", "Sit down", "Tempted."),
    ("Danny's Paper", "A draft on a kitchen table about his big brother as a hero.", "Read it", "Honest.", "Rip it", "Cold."),
    ("Bedroom Confession", "Tattoos, lights, the truth said into a small room at midnight.", "Tell him everything", "Honest.", "Tell him part", "Cold."),
    ("Murray at the Door", "The teacher with a long, polite memory.", "Listen", "Honor.", "Slam the door", "Pride."),
    ("Basketball Court Memory", "A summer game whose score did not matter and a friend who is gone.", "Hold the loss", "Honest.", "Walk past", "Cold."),
    ("Crew Outside the Store", "Cameron's lookouts watching for a new soldier.", "Cross the street", "Wise.", "Confront them", "Pride."),
    ("Bathroom Stall", "A kid from a school you once owned with a small pistol.", "Don't fight", "Wise.", "Reach for it", "Reckless."),
    ("Steps", "Sirens far off, a brother in your arms, a quiet street that has finally arrived.", "Hold him", "Honest.", "Stand", "Lost."),
], [
    ("end_paper", "The Last Page", "Murray reads the rewritten paper at a funeral. The room is full and the words are about a brother and a smile and a curb that should not have happened."),
    ("end_school", "Murray's Class, Front Row", "You sit in the seat your brother used. You raise your hand a lot. The class learns to listen to you because you have, finally, listened back."),
    ("end_quiet", "Doris on the Porch", "Your mother holds your hand on a sagging step at sunset. Neither of you speaks. The neighbors do not yet trust you. You do not blame them."),
])

FM_GRAVE_OF_FIREFLIES = linear_story({
    "id": "fm-grave-of-fireflies",
    "title": "Kobe, 1945",
    "sourceTitle": "Grave of the Fireflies",
    "kind": "movie",
    "synopsis": "An older brother, a younger sister, a candy tin of fruit drops, and a country that has run out of room for them.",
    "releaseYear": 1988, "addedAt": ADDED, "genre": "Drama",
    "tags": ["war", "siblings", "ghibli", "loss"], "rating": 5, "loved": True,
}, [
    ("Air Raid Siren", "A B-29 drone over a wooden city.", "Run for the shelter", "Smart.", "Bury the rice", "Practical."),
    ("Mother's Hospital", "Her face wrapped, only her hand visible on a sheet.", "Tell Setsuko", "Honest.", "Lie", "Mercy."),
    ("Aunt's House", "A relative with a small bowl and a long suspicion.", "Help her", "Polite.", "Stay quiet", "Tired."),
    ("Father's Letter", "He has not written in a month. The navy is the sea.", "Hope", "Heart.", "Plan", "Wise."),
    ("Setsuko's Doll", "A small thing held tight in the dark.", "Tell a story", "Heart.", "Sleep", "Tired."),
    ("Rice Allotment", "Smaller this week, again.", "Buy on black market", "Reckless.", "Ration", "Discipline."),
    ("Beach", "Crabs in tidal pools, a sister laughing for the first time in a week.", "Splash", "Heart.", "Watch", "Honest."),
    ("Bombing of a Field", "Mother's kimono swapped for a cup of rice.", "Trade it", "Practical.", "Keep it", "Heart."),
    ("Aunt's Tongue", "She says the boy should be working at a factory.", "Move out", "Pride.", "Apologize", "Wise."),
    ("Abandoned Shelter", "A concrete hole by a pond and a thicket of fireflies in the doorway.", "Make it home", "Brave.", "Beg to return", "Wise."),
    ("Fireflies", "A canopy of small lights inside a mosquito net.", "Catch them all", "Heart.", "Let them go", "Wise."),
    ("Morning", "The fireflies are dead at the bottom of the net.", "Bury them", "Honest.", "Hide it", "Mercy."),
    ("Setsuko's Cough", "A rasp that should not be in a four-year-old's chest.", "Walk to the doctor", "Care.", "Wait", "Hope."),
    ("Stealing Tomatoes", "A farmer's bamboo cane across your back.", "Apologize", "Wise.", "Defy", "Pride."),
    ("Air Raid", "Bombs in someone else's neighborhood and a chance at empty pantries.", "Loot", "Reckless.", "Stay still", "Honest."),
    ("Bank Telegram", "Your father's ship was lost months ago.", "Withdraw everything", "Wise.", "Sit on the bench", "Lost."),
    ("Watermelon", "A small green coin of mercy on a wooden floor.", "Cut it small", "Heart.", "Eat first", "Selfish."),
    ("Setsuko's Mud Cookies", "She insists they are food and she is too tired to argue.", "Pretend to eat", "Mercy.", "Correct her", "Cold."),
    ("Last Hand", "Her fingers closing weakly around the lid of the candy tin.", "Hold her", "Heart.", "Run for help", "Brave."),
    ("Pyre by the Shelter", "Straw and a small body and a fire that is the wrong fire to make.", "Light it", "Honest.", "Wait", "Lost."),
    ("Train Station", "Boys like you on a platform, ribs visible, a janitor sweeping past with a broom.", "Sit down", "Tired.", "Walk on", "Stubborn."),
], [
    ("end_tin", "The Candy Tin", "A janitor opens a tin and shakes the bones into the grass and you watch from somewhere that is not quite anywhere, and Setsuko comes to meet you."),
    ("end_aunt", "Apology", "You go back to your aunt's house with your head low and you survive the war by inches, and you spend the rest of your life writing a sister letters she will not read."),
    ("end_quiet", "Hill of Lights", "Fireflies above the city, your sister's hand small in yours, the war over somewhere you will never need to go again."),
])

DRAMA_SPECS = [FM_GODFATHER_II, FM_12_ANGRY_MEN, FM_FIGHT_CLUB, FM_ONE_FLEW_OVER, FM_WONDERFUL_LIFE,
               FM_PRESTIGE, FM_DEPARTED, FM_GREEN_MILE, FM_AMERICAN_HISTORY_X, FM_GRAVE_OF_FIREFLIES]
