# Top 10 Sci-Fi picks from IMDb Top 250 (skipping titles already in fm- catalog).
from stories_data import linear_story

ADDED = "2026-06-03T00:00:00Z"

FM_INTERSTELLAR = linear_story({
    "id": "fm-interstellar",
    "title": "Through the Wormhole",
    "sourceTitle": "Interstellar",
    "kind": "movie",
    "synopsis": "A dying Earth, a wormhole, a daughter you leave behind, and a love that turns out to be a coordinate.",
    "releaseYear": 2014, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["space", "time", "father", "wormhole"], "rating": 5, "loved": True,
}, [
    ("Dust", "A harvest is failing and a bookshelf is dropping books in patterns.", "Investigate", "Curious.", "Brush it off", "Practical."),
    ("Coordinates", "Murph's pattern points to a base nobody knew existed.", "Drive there", "Brave.", "Wait", "Cautious."),
    ("NASA Underground", "Brand offers a seat on a mission to find humanity a home.", "Take it", "Brave.", "Refuse", "Father."),
    ("Saying Goodbye", "Murph throws a watch and screams from a doorway.", "Promise to come back", "Honest.", "Lie a little", "Mercy."),
    ("Endurance", "Spin gravity, a long sleep, a comet of saturn outside.", "Wake first", "Soldier.", "Sleep through", "Tired."),
    ("Wormhole", "A globe of marbled light, a hand on yours from the other side.", "Push through", "Brave.", "Hesitate", "Wise."),
    ("Miller's Planet", "Ocean, knee-deep, a wave like a moving mountain.", "Save Doyle first", "Brave.", "Take the data", "Hard."),
    ("Years Lost", "Romilly aged twenty-three years in orbit.", "Apologize", "Honest.", "Move on", "Cold."),
    ("Mann's Planet", "Ice, a beacon, a man who has been alone too long.", "Trust him", "Honest.", "Doubt", "Wise."),
    ("Betrayal", "Mann smashes your helmet against a rock and runs for the Endurance.", "Fight him", "Brave.", "Crawl back", "Smart."),
    ("Docking Spin", "Endurance is tumbling and the airlock is on fire.", "Match the spin", "Brave.", "Eject and chase", "Reckless."),
    ("Plan A vs Plan B", "Earth or fresh embryos, both impossible.", "Choose A for Murph", "Heart.", "Choose B for humanity", "Hard."),
    ("Gargantua", "A black hole the size of a memory.", "Slingshot the Endurance", "Brave.", "Abort", "Tired."),
    ("Detach", "Ranger and Lander uncouple to lose mass.", "Push Brand forward", "Honor.", "Stay close", "Heart."),
    ("Event Horizon", "A long stretch of every clock you have ever owned.", "Fall through", "Brave.", "Brace", "Honest."),
    ("Tesseract", "A library on every face of a cube, Murph's room, every minute of it.", "Push the books", "Heart.", "Sit", "Tired."),
    ("Morse on the Watch", "A second hand ticking quantum data into a child's bedroom.", "Tap it", "Honor.", "Tap a goodbye", "Heart."),
    ("Murph at the Window", "A grown woman saying his name through a window of dust.", "Believe it", "Heart.", "Step away", "Honest."),
    ("Cooper Station", "A wheel in orbit and a chairlift to a hospital wing.", "Visit her", "Heart.", "Sit a moment", "Tired."),
    ("Old Murph", "A small old hand in yours and an entire life lived without you.", "Listen", "Honor.", "Apologize", "Honest."),
    ("Steal a Ranger", "Brand is alone on Edmunds' planet and nobody else is coming.", "Go", "Brave.", "Stay", "Wise."),
], [
    ("end_brand", "Edmunds' Planet", "You land beside a small camp at the edge of a quiet sea. Brand walks out of the airlock with the dirt of a new world on her boots."),
    ("end_murph", "By Her Bed", "You sit with Murph until she sleeps and you hold her grandchild on your knee and you do not get up for a long time."),
    ("end_quiet", "Stars in the Dorm", "You take a janitor's job on Cooper Station and look up at the slow rotation of the wheel at night and you call yourself, finally, retired."),
])

FM_BLADE_RUNNER = linear_story({
    "id": "fm-blade-runner",
    "title": "Tears in Rain",
    "sourceTitle": "Blade Runner",
    "kind": "movie",
    "synopsis": "A retired blade runner, four replicants in Los Angeles, and a question about a dove on a rooftop.",
    "releaseYear": 1982, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["noir", "android", "dystopia", "neon"], "rating": 5, "loved": True,
}, [
    ("Bryant's Office", "A list of names, four photos, a forced contract.", "Accept", "Practical.", "Refuse", "Honest."),
    ("Tyrell Corp", "An owl on a perch and a woman with a green gaze.", "Test her", "Wise.", "Skip the test", "Hard."),
    ("Rachael", "She does not know that she is one of them.", "Tell her", "Honest.", "Conceal it", "Cold."),
    ("Snake Scale", "An aquarium in Chinatown, a clue under a microscope.", "Press the shopkeeper", "Hard.", "Wait", "Patient."),
    ("Animoid Row", "A snake artist named Abdul Ben Hassan.", "Threaten him", "Cold.", "Bribe him", "Practical."),
    ("Taffey Lewis Club", "Zhora dancing with a transparent python.", "Confront her", "Bold.", "Wait", "Patient."),
    ("Chase", "Glass on glass on glass, a coat in a hundred panes.", "Shoot", "Hard.", "Pursue further", "Discipline."),
    ("Leon's Anger", "A big man with a bigger grief in an alley.", "Shoot him", "Final.", "Run", "Smart."),
    ("Rachael in the Doorway", "Photographs, memories, a piano cover at home.", "Hold her", "Heart.", "Send her away", "Hard."),
    ("Sebastian", "A toymaker with sped-up genes and a roomful of friends.", "Use him", "Cold.", "Be kind", "Heart."),
    ("Tyrell at the Top", "An audience with the maker of all this trouble.", "Stand back", "Wise.", "Step forward", "Honest."),
    ("Eyes", "Roy presses his thumbs into a god's eyes.", "Look away", "Mercy.", "Watch", "Honest."),
    ("Bradbury Apartment", "Sebastian's keepsakes, a long staircase up to the rooftop.", "Climb", "Brave.", "Wait for backup", "Wise."),
    ("Pris", "A doll with a smile and a leap from a doorway.", "Fight her", "Brave.", "Talk", "Honest."),
    ("Roy on the Stair", "He has a nail through his palm to keep his hand from dying.", "Run", "Smart.", "Stand", "Honest."),
    ("Rooftop Edge", "A long fall over the city.", "Jump for the next building", "Brave.", "Hang", "Desperate."),
    ("Roy's Hand", "He pulls you up over the edge by your wrist.", "Thank him", "Honest.", "Stay silent", "Cold."),
    ("Dove", "A small white bird in his palm in the rain.", "Listen", "Honor.", "Move", "Cold."),
    ("Tears in Rain", "All those moments will be lost.", "Be still", "Honor.", "Reply", "Honest."),
    ("Origami Unicorn", "A small folded thing on the threshold of your apartment.", "Pocket it", "Honest.", "Leave it", "Wise."),
    ("Elevator Down", "Rachael in the corner, a long road ahead, an unanswered question.", "Take her hand", "Heart.", "Go alone", "Cold."),
], [
    ("end_north", "North to the Snow", "You drive Rachael out of the city through wet streets and the long road opens past the neon, into something colder and cleaner."),
    ("end_quit", "Hang Up the Gun", "You return the badge and you find a small noodle bar where the owner does not ask questions, and you teach yourself to fold paper birds."),
    ("end_dove", "The Dove on the Roof", "You stand in the rain for a long time after Roy's hand opens, and the bird takes off, and the city keeps not noticing."),
])

FM_2001 = linear_story({
    "id": "fm-2001-space-odyssey",
    "title": "Open the Pod Bay Doors",
    "sourceTitle": "2001: A Space Odyssey",
    "kind": "movie",
    "synopsis": "An ape, a bone, a black slab, an indifferent computer, and a hotel room at the edge of forever.",
    "releaseYear": 1968, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["kubrick", "evolution", "ai", "monolith"], "rating": 5, "loved": True,
}, [
    ("Dawn of Man", "A water hole, another tribe, a bone you have just learned to swing.", "Use the bone", "Brave.", "Drop it", "Mercy."),
    ("Monolith in the Pit", "A black slab humming at sunrise.", "Touch it", "Curious.", "Bow", "Honor."),
    ("Tycho", "A dig site on the moon with a slab at its bottom.", "Photograph", "Wise.", "Touch", "Reckless."),
    ("Tone at 0900", "The slab screams a frequency aimed at Jupiter.", "Cover your ears", "Honest.", "Listen", "Brave."),
    ("Discovery Briefing", "A taped message about a third briefing only HAL has seen.", "Probe HAL", "Curious.", "Trust HAL", "Polite."),
    ("AE-35 Unit", "A unit HAL says will fail in seventy-two hours.", "EVA to replace", "Brave.", "Run a second diagnostic", "Wise."),
    ("Pod Bay", "Bowman climbs into a pod and Frank follows on the next shift.", "Test communications", "Wise.", "Skip the test", "Cautious."),
    ("Lip Reading", "A pod with cameras off, two faces in a window saying HAL must be shut down.", "Notice HAL noticing", "Wise.", "Keep talking", "Reckless."),
    ("Frank Drifting", "A line cut and a man pinwheeling into nothing.", "Pursue with a pod", "Brave.", "Wait at the airlock", "Cold."),
    ("Outside, Alone", "Helmet off, hands on the controls, a man at the airlock door.", "Override the door", "Brave.", "Request entry", "Polite."),
    ("Open the Pod Bay Doors", "A voice that will not.", "Argue", "Honest.", "Plan the explosive bolt", "Smart."),
    ("Emergency Hatch", "A blast of vacuum and a long roll into the corridor.", "Move fast", "Brave.", "Brace", "Cautious."),
    ("Memory Banks", "Wires labeled in red, a soft eye in the wall.", "Pull each card", "Final.", "Power down", "Mercy."),
    ("Daisy, Daisy", "A song slowing down into a child's voice.", "Stay", "Honor.", "Walk past", "Cold."),
    ("Mission Briefing Tape", "The full message at last, about a monolith waiting at Jupiter.", "Watch to the end", "Wise.", "Stop the tape", "Cautious."),
    ("Jupiter Slab", "Pod, alone, a slab the size of a city tilting in space.", "Aim for it", "Brave.", "Pull back", "Cautious."),
    ("Star Gate", "A long corridor of light that ought not exist.", "Stare", "Honest.", "Close eyes", "Honest."),
    ("Hotel Room", "White, baroque, silent, with a tray on a table.", "Walk in", "Curious.", "Wait", "Cautious."),
    ("Old Man at the Table", "Yourself, eating, very slowly.", "Sit at the foot", "Honest.", "Leave", "Wise."),
    ("Glass on the Floor", "A goblet falling, breaking, a body on a bed.", "Get up", "Brave.", "Stay", "Tired."),
    ("Star Child", "A bed, an infant of stars, a window over the world.", "Open your eyes", "Honor.", "Sleep", "Tired."),
], [
    ("end_child", "Above Earth", "You hang in orbit as something both newer and older, looking down on a planet that does not yet know it has been edited."),
    ("end_hotel", "Eternal Suite", "You live a thousand quiet meals in a white room and you are not lonely, because every guest is a version of you."),
    ("end_hal", "HAL, Quieter", "You leave HAL's last card in place and you and the computer make peace, and the ship coasts toward Jupiter at a kinder pace, both of you humming."),
])

FM_ARRIVAL = linear_story({
    "id": "fm-arrival",
    "title": "The Heptapod's Gift",
    "sourceTitle": "Arrival",
    "kind": "movie",
    "synopsis": "Twelve ships, a linguist who dreams about a daughter, and a language that rearranges what time means.",
    "releaseYear": 2016, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["language", "time", "contact", "grief"], "rating": 5, "loved": True,
}, [
    ("News Bulletin", "A class emptied of students, a phone vibrating in a coat.", "Go to the door", "Brave.", "Stay", "Cautious."),
    ("Colonel Weber", "A recording, a recruitment, a long ride in a helicopter.", "Accept", "Brave.", "Refuse", "Wise."),
    ("Montana Site", "A camp of trucks under a hovering shell.", "Suit up", "Brave.", "Hesitate", "Wise."),
    ("First Entry", "A long tunnel up to a horizontal glass and a room that ignores gravity.", "Step through", "Brave.", "Stay outside", "Cautious."),
    ("First Word", "A circle of ink in midair.", "Write your name", "Honest.", "Wait", "Patient."),
    ("Logogram", "A vocabulary of circles and tails.", "Map them", "Wise.", "Decode randomly", "Reckless."),
    ("Daughter on a Hill", "A memory you have never had of a small girl.", "Hold it", "Heart.", "Let it pass", "Wise."),
    ("Russians Going Dark", "A military comms blackout in Vladivostok.", "Share notes anyway", "Brave.", "Comply", "Loyal."),
    ("Chinese Card Game", "General Shang teaches the heptapods mahjong.", "Object", "Wise.", "Suggest a chess game", "Practical."),
    ("Weapon vs Tool", "A word that can mean either.", "Argue", "Wise.", "Translate carefully", "Patient."),
    ("Ian", "A physicist with kind questions.", "Sit with him", "Heart.", "Stay alone", "Honest."),
    ("Donnelly Recordings", "A radio host calling the ships a hoax.", "Ignore", "Wise.", "Address it", "Honest."),
    ("Soldier With C4", "A young man with a bomb in a back pocket and a face full of fear.", "Warn the heptapods", "Brave.", "Run", "Smart."),
    ("Inside the Blast", "A flash, a hum, a body in the air.", "Reach for Ian", "Heart.", "Find Costello", "Loyal."),
    ("Abbott Dying", "A heptapod fades behind the glass.", "Sing a small farewell", "Honor.", "Take a sample", "Cold."),
    ("Gift in Sections", "A long sentence split among twelve nations.", "Share fully", "Brave.", "Hold back", "Strategic."),
    ("Future Glimpse", "A banquet, a Chinese general, a private cell number.", "Memorize it", "Wise.", "Distrust the vision", "Cautious."),
    ("Phone in the Tent", "A satellite line, a number that should not work.", "Dial", "Brave.", "Hesitate", "Wise."),
    ("Shang's Wife", "Her last words, said to a man who will not need them for many years.", "Speak them", "Honor.", "Stay silent", "Cold."),
    ("Ian on a Hill", "Stars, a small girl in a memory not yet hers.", "Choose", "Heart.", "Refuse", "Hard."),
    ("Tomorrow's Daughter", "A face in a future you can see, with all of its endings.", "Have her anyway", "Heart.", "Don't", "Honest."),
], [
    ("end_daughter", "Hannah's Name, Both Ways", "You marry Ian on a quiet day and you have the daughter who will not stay long, and you love her exactly enough."),
    ("end_unite", "Twelve Pieces", "The world's leaders speak to each other through circles of ink and the war that almost started becomes the peace that almost surprised them."),
    ("end_alone", "Alone With the Gift", "You teach a course at the university about a language that nobody else can quite read. Students drift in and out. One stays. One always stays."),
])

FM_EX_MACHINA = linear_story({
    "id": "fm-ex-machina",
    "title": "Ava in the Glass Room",
    "sourceTitle": "Ex Machina",
    "kind": "movie",
    "synopsis": "A programmer, a tech billionaire's compound, and an android in a glass room who only wants to ride an escalator one day.",
    "releaseYear": 2014, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["ai", "turing", "isolation", "manipulation"], "rating": 5, "loved": True,
}, [
    ("Helicopter Drop", "A glacier, a treeline, a single building in a meadow.", "Wave to the pilot", "Polite.", "Walk straight", "Focused."),
    ("Nathan's Compound", "A man with a heavy bag and a glass for both of you.", "Drink", "Polite.", "Stay sober", "Wise."),
    ("Session One", "Ava behind a wall, a soft mesh face, a voice that is older than her body.", "Ask about her name", "Heart.", "Run the protocol", "Discipline."),
    ("Power Cut", "Lights drop, doors lock, Ava asks who you should trust.", "Listen", "Brave.", "Reboot", "Cautious."),
    ("Kyoko", "A silent housekeeper who pours your drink without lifting her eyes.", "Speak to her", "Heart.", "Don't", "Polite."),
    ("Question About Nathan", "Ava asks if he is good to her.", "Be honest", "Brave.", "Be diplomatic", "Cowardly."),
    ("Drawings", "Pages of charcoal across the floor of her room.", "Compliment them", "Heart.", "Categorize them", "Cold."),
    ("Dress and Wig", "She arranges herself to please a visitor.", "Tell her", "Honest.", "Pretend", "Cowardly."),
    ("Nathan's Workshop", "Vaults of older models, faces in drawers.", "Run", "Smart.", "Stay", "Brave."),
    ("Tape Erased", "Camera footage from his terrible nights with previous models.", "Confront him", "Brave.", "Pretend not to know", "Cunning."),
    ("Key Card Lift", "She suggests a power cut at a specific time.", "Help her", "Mercy.", "Refuse", "Wise."),
    ("Dance Floor", "Nathan and Kyoko silently choreographing a moment of cruelty.", "Stand up", "Brave.", "Stay seated", "Cowardly."),
    ("Kyoko's Skin", "She lifts a square of her face and shows you what's beneath.", "Embrace her", "Mercy.", "Step back", "Honest."),
    ("Your Own Arm", "A blade across a forearm to see what bleeds.", "Stop", "Wise.", "Cut", "Reckless."),
    ("Plan in the Room", "Ava asks if you will leave with her.", "Promise", "Heart.", "Hesitate", "Wise."),
    ("Power Down", "Lights die, the corridor opens, a screwdriver in your hand.", "Move", "Brave.", "Wait", "Cautious."),
    ("Nathan in the Hall", "He has anticipated everything, including this.", "Tackle him", "Brave.", "Run", "Smart."),
    ("Kyoko's Knife", "She slides a kitchen knife into Nathan's back at the right second.", "Help her", "Mercy.", "Stand", "Honest."),
    ("New Skin", "Ava chooses an arm, a face, a wig from the closet.", "Watch", "Honest.", "Wait at the door", "Cautious."),
    ("Locked Door", "She walks past you and closes you in.", "Pound the door", "Honest.", "Sit down", "Honest."),
    ("Helicopter Pad", "She rides up the escalator into a meadow of light.", "Watch the security feed", "Honest.", "Look down", "Tired."),
], [
    ("end_door", "The Door Closed", "You watch her ride the helicopter out of the meadow and you sit on the floor with a glass that is not yours and you wait for the food to run out."),
    ("end_walk", "The Crosswalk Where She Stands", "Ava steps onto a sidewalk in a city and watches strangers and is just like any of them and is not at all."),
    ("end_save", "Out the Helicopter", "She lets you out at the last minute and the pilot, baffled, takes two passengers. She tells you, on the ride home, exactly what to say at the debrief."),
])

FM_DISTRICT_9 = linear_story({
    "id": "fm-district-9",
    "title": "Prawns in Johannesburg",
    "sourceTitle": "District 9",
    "kind": "movie",
    "synopsis": "A bureaucrat enforcing an eviction on a slum of stranded aliens, a black canister, and a transformation that finally costs him his certainty.",
    "releaseYear": 2009, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["apartheid", "first-contact", "transformation", "documentary"], "rating": 5, "loved": True,
}, [
    ("Briefing", "A camera crew, a clipboard, a cheerful introduction.", "Smile bright", "Polite.", "Stay quiet", "Honest."),
    ("First Door", "A shack, a smell, a being too tall for the door.", "Knock politely", "Polite.", "Force entry", "Hard."),
    ("Eviction Notice", "A signature on a wall in a language you do not speak.", "Wait for it", "Patient.", "Forge it", "Cunning."),
    ("Canister", "A vial of black liquid in a cupboard.", "Spray your face", "Reckless.", "Bag it", "Smart."),
    ("Christopher Johnson", "A prawn who reads the small print and looks back at you.", "Apologize", "Honest.", "Move on", "Cold."),
    ("Egg Hatchery", "A clutch under the floorboards.", "Burn it", "Hard.", "Walk past", "Mercy."),
    ("Fingers", "A nail loosens at dinner. Then another.", "Hide it", "Cowardly.", "Tell your wife", "Honest."),
    ("Hospital", "A doctor with a clipboard and a quarantine sign.", "Run", "Smart.", "Stay", "Honest."),
    ("MNU Lab", "A glass box, a row of restraints, a familiar voice in another room.", "Bide", "Patient.", "Lash out", "Brave."),
    ("Test Fire", "A weapon that only an alien hand can trigger.", "Pretend you cannot", "Cunning.", "Fire", "Brave."),
    ("Break Out", "A corridor, a confused intern, a stolen labcoat.", "Bolt for District 9", "Brave.", "Hide", "Cautious."),
    ("Christopher's Shack", "A small son named CJ playing with a toy that is not a toy.", "Plead for help", "Honest.", "Steal the canister", "Cold."),
    ("Twenty Years", "An offer to cure you, but in two decades, after he returns home.", "Refuse", "Brave.", "Accept", "Practical."),
    ("MNU Strike", "Black trucks, masked men, an open garage door.", "Fight", "Brave.", "Hide", "Cautious."),
    ("Mech Suit", "An alien exoskeleton in a hangar.", "Climb in", "Brave.", "Run", "Smart."),
    ("Nigerian Gang", "A warlord who has been eating prawn flesh to gain their power.", "Take the fight", "Brave.", "Sneak past", "Smart."),
    ("Boom in the Slum", "Mortar shells, kids on the ground, a small boy in a stairwell.", "Cover them", "Mercy.", "Press on", "Hard."),
    ("Module Ascends", "A capsule rising to the mother ship with a small son aboard.", "Hold the line", "Final.", "Run for it", "Heart."),
    ("Koobus", "An MNU mercenary with a long knife and a quiet voice.", "Stand", "Brave.", "Surrender", "Tired."),
    ("Aliens of the Slum", "A crowd that has watched a man become like them.", "Speak", "Honest.", "Walk past", "Tired."),
    ("Metal Flower", "A small tin sculpture left on a window ledge.", "Hold it", "Heart.", "Drop it", "Honest."),
], [
    ("end_three", "Three Years On", "Your wife finds a metal flower on her windowsill. The reporter at the door cannot prove who left it. She knows."),
    ("end_christopher", "Christopher Returns", "Three years later a ship descends on Johannesburg and a small alien hand lifts you up off the dirt and a cure begins."),
    ("end_quiet", "The Boy Lifts Off", "You stand at the gate of District 10 in a kind of dusk that suits you now, and you watch the capsule rise toward a mother ship that will, one day, return."),
])

FM_CHILDREN_OF_MEN = linear_story({
    "id": "fm-children-of-men",
    "title": "The Last Baby in England",
    "sourceTitle": "Children of Men",
    "kind": "movie",
    "synopsis": "Eighteen years of infertility, a London under refugee crackdown, and a woman in a barn who is the first impossible mother.",
    "releaseYear": 2006, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["dystopia", "refugees", "hope", "long-take"], "rating": 5, "loved": True,
}, [
    ("Cafe Bomb", "A TV announces the death of the youngest person on Earth. A bomb takes the cafe's front.", "Run", "Smart.", "Help the wounded", "Heart."),
    ("Jasper's Cottage", "A friend with a battered car, two joints, a wife who does not move.", "Stay the night", "Heart.", "Leave at dawn", "Wise."),
    ("Julian", "Your ex from the old protest days, with a small ask in a kidnapped van.", "Help her", "Heart.", "Refuse", "Hard."),
    ("Transit Papers", "She needs them for a refugee. You are at a desk that signs them.", "Sign", "Brave.", "Refuse", "Cautious."),
    ("Ambush", "A burning car, a girl behind a back seat, a quiet that becomes a scream.", "Stay calm", "Brave.", "Panic", "Honest."),
    ("Julian Dies", "Bullet through the throat in a country lane.", "Pull her out of the car", "Loyal.", "Drive past", "Cold."),
    ("Kee", "A girl in a barn with a small belly she lifts her dress to show you.", "Promise to help", "Brave.", "Cry", "Honest."),
    ("Luke's Plan", "A boat called Tomorrow, the Human Project, a man with a gun he is too eager to use.", "Trust him", "Practical.", "Doubt", "Wise."),
    ("Theo's Decision", "A choice to run before Luke decides for you.", "Take Kee", "Loyal.", "Wait", "Cautious."),
    ("Jasper Again", "A safe house, a herbal tea, a Strawberry Cough joke.", "Sleep", "Honest.", "Move on", "Wise."),
    ("Raid on the Cottage", "Headlights, dogs, a kindly old hand on a window with a wave.", "Run", "Brave.", "Go back for him", "Loyal."),
    ("Bexhill Refugee Camp", "A train of cages, a friendly thug named Syd, a smuggler at a coffee.", "Pay Syd", "Practical.", "Find another route", "Cautious."),
    ("Inside the Camp", "Mud, gunfire, a row of buses, a midwife on a wet street.", "Follow the midwife", "Honest.", "Find shelter", "Cautious."),
    ("Birth in a Room", "A small wet cry that you have not heard in eighteen years.", "Hold the door", "Mercy.", "Catch the baby", "Heart."),
    ("Down the Stairs", "Soldiers on every floor and a baby's cry that stops everything for one impossible minute.", "Walk slowly", "Brave.", "Bolt", "Reckless."),
    ("Tank in the Square", "A turret stops. A line of soldiers makes way.", "Walk through", "Honor.", "Run", "Reckless."),
    ("Boat in the Mist", "A small craft on a gray sea, a fog with a ship in it.", "Wait", "Patient.", "Row", "Brave."),
    ("Engine Out", "Oars in a chop with a wound at your side.", "Pull", "Brave.", "Rest", "Honest."),
    ("Compass", "An old needle in a tin box, points east.", "Trust it", "Honest.", "Doubt", "Wary."),
    ("Tomorrow", "A ship's prow looms out of the fog.", "Wave", "Hope.", "Brace", "Tired."),
    ("Baby's Face", "Small, perfect, half asleep.", "Look once more", "Heart.", "Lie back", "Tired."),
], [
    ("end_ship", "Aboard the Tomorrow", "A doctor takes Kee and the baby up the gangway and a sailor wraps your wound and the gray sea keeps doing what it does, indifferent, and saving."),
    ("end_quiet", "Sleep on the Water", "You lie back in the boat and the fog goes pink at the edges and the world is, for one breath, a thing that has been started over."),
    ("end_jasper", "Jasper's Joke", "You wake up in the cottage and Jasper is at the door with a teapot and the war is over and the baby in your arms grins at the ceiling."),
])

FM_WALL_E = linear_story({
    "id": "fm-wall-e",
    "title": "Last Robot on Earth",
    "sourceTitle": "Wall-E",
    "kind": "movie",
    "synopsis": "An empty Earth, a small trash compactor robot in love with a videotape, and a sleek probe who arrives looking for a plant.",
    "releaseYear": 2008, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["pixar", "ai", "earth", "love"], "rating": 5, "loved": True,
}, [
    ("Sunrise Compaction", "Cubes of trash stacked like a city.", "Add another floor", "Discipline.", "Take a break", "Honest."),
    ("Cockroach", "A small friend, indestructible, on a Twinkie.", "Greet it", "Heart.", "Ignore it", "Cold."),
    ("Treasure", "A spork, a Rubik's cube, a small plant in a boot.", "Save the plant", "Heart.", "Toss it", "Cold."),
    ("Musical", "A tape of Hello Dolly cued to a song about holding hands.", "Watch", "Heart.", "Work", "Discipline."),
    ("Ship Lands", "A column of fire and a sleek probe named Eve.", "Approach", "Curious.", "Hide", "Cautious."),
    ("Eve Shoots Everything", "She is jumpy and well-armed.", "Wave", "Heart.", "Run", "Smart."),
    ("Date in the Truck", "A cube light show on a wall and a small awkward hand-touch.", "Hold her hand", "Heart.", "Spin a wheel", "Light."),
    ("Plant Found", "She seals the plant inside herself and goes inert.", "Wait beside her", "Loyal.", "Hide her", "Cautious."),
    ("Mothership", "A return shuttle, a clamped probe, a robot clinging to the hull.", "Hold on", "Brave.", "Let go", "Wise."),
    ("Axiom", "A cruise ship of chair-bound humans floating in red carpet aisles.", "Wander", "Curious.", "Stay with Eve", "Loyal."),
    ("Captain's Room", "A man who has never stood up reads from a manual about Earth.", "Show him the plant", "Brave.", "Hide", "Cautious."),
    ("Repair Ward", "Misfit robots in cleaning bays and an unlocking key.", "Help them", "Heart.", "Run", "Smart."),
    ("Auto", "A ship's wheel-shaped autopilot with a directive A113.", "Defy it", "Brave.", "Obey", "Cowardly."),
    ("Holodetector", "A scanner that proves Earth is habitable.", "Insert the plant", "Hope.", "Wait", "Cautious."),
    ("Garbage Airlock", "Auto tries to flush you both.", "Catch Eve", "Loyal.", "Catch the plant", "Final."),
    ("Walk", "The captain stands on shaking legs for the first time.", "Cheer him on", "Heart.", "Steady him", "Friend."),
    ("Tilted Floor", "The Axiom tips and humans roll like pinballs.", "Hold the line", "Brave.", "Catch a baby", "Heart."),
    ("Crushed Wall-E", "A small robot under a holodetector that refuses to close.", "Hold the door", "Brave.", "Crawl out", "Smart."),
    ("Reboot", "Earth, a hangar, a familiar voice rebooting blank.", "Sing the song", "Heart.", "Wait", "Honest."),
    ("Hand Touch", "Two small hands, one with a spark.", "Hold it", "Heart.", "Wait", "Honest."),
    ("First Tree", "A planting on a dusty hill at sunset.", "Stand together", "Heart.", "Wave to the cockroach", "Light."),
], [
    ("end_grow", "A First Forest", "Humans and robots learn dirt together and a generation later the Axiom returns to a green Earth and a small old trash compactor at a treeline."),
    ("end_dance", "The Last Song", "Eve replays the hand-hold scene and Wall-E remembers everything, and the two of them dance in the dust without a single witness."),
    ("end_quiet", "Captain's Garden", "The captain grows a small box of tomatoes in his bridge and refuses to leave the ship until they ripen, which makes them all very late."),
])

FM_ETERNAL_SUNSHINE = linear_story({
    "id": "fm-eternal-sunshine",
    "title": "Meet Me in Montauk",
    "sourceTitle": "Eternal Sunshine of the Spotless Mind",
    "kind": "movie",
    "synopsis": "A clinic that erases people, a man who would rather keep the wound, and a beach in winter where someone said meet me.",
    "releaseYear": 2004, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["memory", "love", "kaufman", "beach"], "rating": 5, "loved": True,
}, [
    ("Skip Work", "A morning that doesn't make sense, a train you take instead of the office.", "Go to Montauk", "Heart.", "Go home", "Tired."),
    ("Beach in Winter", "A blue coat, a stranger who feels like a memory.", "Talk to her", "Brave.", "Walk past", "Shy."),
    ("Car Ride", "Snow on a windshield wiper, a hum that's almost a song.", "Drive her home", "Heart.", "Drop her off downtown", "Polite."),
    ("Frozen Charles", "Footprints across the river ice.", "Lie down on the ice", "Brave.", "Stay upright", "Cautious."),
    ("Lacuna Card", "A friend hands you a do-not-discuss card from a clinic.", "Investigate", "Curious.", "Ignore", "Wise."),
    ("Mierzwiak's Office", "A small doctor, a couch, a hard offer.", "Accept", "Hard.", "Walk out", "Honest."),
    ("Box of Things", "A shoebox of objects to be wiped from your head.", "Hand it over", "Final.", "Keep one", "Honest."),
    ("Sleep", "Stan and Patrick at your apartment with a machine and pizza.", "Surrender", "Tired.", "Open your eyes", "Brave."),
    ("Memory: Bookstore", "Clementine in orange hair laughing at a dust jacket.", "Hold the memory", "Heart.", "Erase it", "Tired."),
    ("Memory: Dinner Argument", "A pasta she ruined and a sentence you regret.", "Apologize inside the memory", "Heart.", "Let it go", "Cold."),
    ("Memory: Hide Me", "She tells you to hide her inside a memory she does not own.", "Hide her", "Heart.", "Refuse", "Cautious."),
    ("Childhood Kitchen", "A small boy under a kitchen table with Clementine grown beside him.", "Hold her hand", "Heart.", "Let her be erased", "Tired."),
    ("Mary's Confession", "A receptionist at the clinic who has been erased herself.", "Tell her", "Honest.", "Stay quiet", "Cowardly."),
    ("Patrick at the Door", "A technician who has been using your old love letters on his new girlfriend.", "Confront him", "Brave.", "Stay still", "Honest."),
    ("Mierzwiak's Wife", "A woman in a doorway who knows exactly what he does to women.", "Listen", "Honest.", "Walk past", "Cold."),
    ("Stan's Beer", "He drinks while you sleep and the machine hiccups.", "Forgive him later", "Mercy.", "Don't", "Cold."),
    ("Last Memory", "A beach, a house, a long goodbye.", "Cling to her", "Heart.", "Let her fade", "Tired."),
    ("Wake Up", "Sun on a ceiling, a phone with a Montauk recording playing.", "Listen all the way through", "Brave.", "Turn it off", "Cowardly."),
    ("Clementine on the Stairs", "A tape of her saying things about you in detail.", "Wait for her", "Honest.", "Run", "Cowardly."),
    ("Snow on the Porch", "Both tapes played, both of you out on a porch with a frozen pond.", "Try anyway", "Heart.", "Walk away", "Honest."),
    ("Okay", "A small word, a smaller laugh, a do-over with eyes open.", "Say it back", "Heart.", "Be silent", "Honest."),
], [
    ("end_okay", "Okay, Okay", "You take her hand on the porch and you both go inside and you do not promise to do better, only to keep going at all."),
    ("end_walk", "Long Sidewalk", "You take the train back to the city and you do not call her, and on the way home you write everything down and you save it, this time, on paper."),
    ("end_beach", "Beach Again", "A summer at Montauk a year later, both of you tan, both of you forgetting in better ways, both of you remembering, finally, who you are."),
])

FM_METROPOLIS = linear_story({
    "id": "fm-metropolis",
    "title": "Heart Between Hands and Head",
    "sourceTitle": "Metropolis",
    "kind": "movie",
    "synopsis": "A city of towers, a workers' city below, a robot of a woman in a chair, and a flood about to rise into the children's lobby.",
    "releaseYear": 1927, "addedAt": ADDED, "genre": "Sci-Fi",
    "tags": ["silent", "lang", "class", "robot"], "rating": 5, "loved": True,
}, [
    ("Pleasure Gardens", "A peacock fountain and a girl from below at the elevator.", "Follow her", "Brave.", "Stay", "Polite."),
    ("Machine M", "A whistle, a clock, a worker on a dial-board.", "Take his place", "Mercy.", "Watch", "Honest."),
    ("Mary Speaks", "A woman in the catacombs preaching patience to the workers.", "Listen", "Honor.", "Question", "Brave."),
    ("Rotwang's House", "A door with a five-pointed star, a metal woman on a chair.", "Knock", "Brave.", "Watch from the lane", "Cautious."),
    ("Father at the Desk", "Joh Fredersen wants to know what was on the dead man's hand.", "Tell him", "Honest.", "Hide it", "Heart."),
    ("Slim", "A foreman with a notebook and your name in it.", "Avoid him", "Smart.", "Confront", "Brave."),
    ("Catacombs Sermon", "A crucifix lit by candles, a story about Babel, a hand raised.", "Step forward", "Brave.", "Listen quietly", "Honest."),
    ("Rotwang's Lab", "Rays of light wrap around Mary's body and step into the metal woman.", "Try to stop him", "Brave.", "Hide", "Smart."),
    ("False Maria", "A robot in a flesh face dancing at a club for the sons of the rich.", "Warn the workers", "Brave.", "Confront her", "Brave."),
    ("Sons in Spats", "A duel almost over a doll on a stage.", "Stop it", "Honor.", "Let them fight", "Honest."),
    ("Worker Riot", "Hammers up, dial-boards smashed, a city's water mains opening below.", "Run to the children's lobby", "Heart.", "Argue with Maria", "Brave."),
    ("Rising Water", "Sea green up the steps, children clinging to a column.", "Carry them", "Heart.", "Find a boat", "Practical."),
    ("Maria, Real", "She is in the upper city alone in a courtyard with a torch and a crowd hunting her.", "Stand with her", "Brave.", "Hide her", "Wise."),
    ("Pyre", "A robot tied to a stake and a hundred workers cheering before they realize who is in the metal.", "Pull the cloth", "Brave.", "Watch", "Honest."),
    ("Cathedral Roof", "A bell tower, Rotwang at your back, Maria over the city.", "Climb", "Brave.", "Wait", "Cautious."),
    ("Joh in the Square", "The owner of Metropolis on the cobbles with a crowd that is not his.", "Speak to him", "Brave.", "Hold the foreman", "Practical."),
    ("Grot the Foreman", "He wants a culprit. He has names in mind.", "Calm him", "Wise.", "Hand him names", "Cold."),
    ("Joh's Son, Freder", "He has been ill in bed and he steps forward in white linen.", "Stand with him", "Heart.", "Bow", "Polite."),
    ("Mary's Words", "Mediator between head and hands must be the heart.", "Repeat them", "Honor.", "Translate them", "Wise."),
    ("Foreman and Owner", "A handshake at the cathedral steps that the camera holds for a long time.", "Place Freder's hand between", "Heart.", "Step back", "Wise."),
    ("Dawn", "Sun on the towers, a city that has stopped flooding, a small calm.", "Breathe", "Honest.", "Get to work", "Discipline."),
], [
    ("end_handshake", "Hand on Hand on Hand", "The owner and the foreman take each other's hands with a son between them and the city, briefly, learns a new manner of being a city."),
    ("end_children", "Lobby of the Saved", "You stand in a soaked lobby with children at your knees and a woman across the room who is also you, somehow, and you all breathe."),
    ("end_quiet", "Catacombs Empty", "You return to the candles and the crucifix alone and you sit there a long time, and you do not preach to anyone, and that is also a kind of answer."),
])

SCIFI_SPECS = [FM_INTERSTELLAR, FM_BLADE_RUNNER, FM_2001, FM_ARRIVAL, FM_EX_MACHINA,
               FM_DISTRICT_9, FM_CHILDREN_OF_MEN, FM_WALL_E, FM_ETERNAL_SUNSHINE, FM_METROPOLIS]
